# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@babel/code-frame@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/code-frame/-/code-frame-7.27.1.tgz";
    hash = "sha512-cjQ7ZlQ0Mv3b47hABuTevyTuYN4i+loJKGeV9flcCgIK37cCXRh+L1bd3iBHlynerhQ7BhCkn2BPbQUL+rGqFg==";
    name = "code-frame-7.27.1.tgz";
  };
  "@babel/compat-data@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/compat-data/-/compat-data-7.28.5.tgz";
    hash = "sha512-6uFXyCayocRbqhZOB+6XcuZbkMNimwfVGFji8CTZnCzOHVGvDqzvitu1re2AU5LROliz7eQPhB8CpAMvnx9EjA==";
    name = "compat-data-7.28.5.tgz";
  };
  "@babel/core@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/core/-/core-7.28.5.tgz";
    hash = "sha512-e7jT4DxYvIDLk1ZHmU/m/mB19rex9sv0c2ftBtjSBv+kVM/902eh0fINUzD7UwLLNR+jU585GxUJ8/EBfAM5fw==";
    name = "core-7.28.5.tgz";
  };
  "@babel/generator@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/generator/-/generator-7.28.5.tgz";
    hash = "sha512-3EwLFhZ38J4VyIP6WNtt2kUdW9dokXA9Cr4IVIFHuCpZ3H8/YFOl5JjZHisrn1fATPBmKKqXzDFvh9fUwHz6CQ==";
    name = "generator-7.28.5.tgz";
  };
  "@babel/helper-compilation-targets@7.27.2" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-compilation-targets/-/helper-compilation-targets-7.27.2.tgz";
    hash = "sha512-2+1thGUUWWjLTYTHZWK1n8Yga0ijBz1XAhUXcKy81rd5g6yh7hGqMp45v7cadSbEHc9G3OTv45SyneRN3ps4DQ==";
    name = "helper-compilation-targets-7.27.2.tgz";
  };
  "@babel/helper-globals@7.28.0" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-globals/-/helper-globals-7.28.0.tgz";
    hash = "sha512-+W6cISkXFa1jXsDEdYA8HeevQT/FULhxzR99pxphltZcVaugps53THCeiWA8SguxxpSp3gKPiuYfSWopkLQ4hw==";
    name = "helper-globals-7.28.0.tgz";
  };
  "@babel/helper-module-imports@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-module-imports/-/helper-module-imports-7.27.1.tgz";
    hash = "sha512-0gSFWUPNXNopqtIPQvlD5WgXYI5GY2kP2cCvoT8kczjbfcfuIljTbcWrulD1CIPIX2gt1wghbDy08yE1p+/r3w==";
    name = "helper-module-imports-7.27.1.tgz";
  };
  "@babel/helper-module-transforms@7.28.3" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-module-transforms/-/helper-module-transforms-7.28.3.tgz";
    hash = "sha512-gytXUbs8k2sXS9PnQptz5o0QnpLL51SwASIORY6XaBKF88nsOT0Zw9szLqlSGQDP/4TljBAD5y98p2U1fqkdsw==";
    name = "helper-module-transforms-7.28.3.tgz";
  };
  "@babel/helper-plugin-utils@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-plugin-utils/-/helper-plugin-utils-7.27.1.tgz";
    hash = "sha512-1gn1Up5YXka3YYAHGKpbideQ5Yjf1tDa9qYcgysz+cNCXukyLl6DjPXhD3VRwSb8c0J9tA4b2+rHEZtc6R0tlw==";
    name = "helper-plugin-utils-7.27.1.tgz";
  };
  "@babel/helper-string-parser@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-string-parser/-/helper-string-parser-7.27.1.tgz";
    hash = "sha512-qMlSxKbpRlAridDExk92nSobyDdpPijUq2DW6oDnUqd0iOGxmQjyqhMIihI9+zv4LPyZdRje2cavWPbCbWm3eA==";
    name = "helper-string-parser-7.27.1.tgz";
  };
  "@babel/helper-validator-identifier@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
    hash = "sha512-qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
    name = "helper-validator-identifier-7.28.5.tgz";
  };
  "@babel/helper-validator-option@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helper-validator-option/-/helper-validator-option-7.27.1.tgz";
    hash = "sha512-YvjJow9FxbhFFKDSuFnVCe2WxXk1zWc22fFePVNEaWJEu8IrZVlda6N0uHwzZrUM1il7NC9Mlp4MaJYbYd9JSg==";
    name = "helper-validator-option-7.27.1.tgz";
  };
  "@babel/helpers@7.28.4" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/helpers/-/helpers-7.28.4.tgz";
    hash = "sha512-HFN59MmQXGHVyYadKLVumYsA9dBFun/ldYxipEjzA4196jpLZd8UjEEBLkbEkvfYreDqJhZxYAWFPtrfhNpj4w==";
    name = "helpers-7.28.4.tgz";
  };
  "@babel/parser@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/parser/-/parser-7.28.5.tgz";
    hash = "sha512-KKBU1VGYR7ORr3At5HAtUQ+TV3SzRCXmA/8OdDZiLDBIZxVyzXuztPjfLd3BV1PRAQGCMWWSHYhL0F8d5uHBDQ==";
    name = "parser-7.28.5.tgz";
  };
  "@babel/plugin-transform-react-jsx-self@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/plugin-transform-react-jsx-self/-/plugin-transform-react-jsx-self-7.27.1.tgz";
    hash = "sha512-6UzkCs+ejGdZ5mFFC/OCUrv028ab2fp1znZmCZjAOBKiBK2jXD1O+BPSfX8X2qjJ75fZBMSnQn3Rq2mrBJK2mw==";
    name = "plugin-transform-react-jsx-self-7.27.1.tgz";
  };
  "@babel/plugin-transform-react-jsx-source@7.27.1" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/plugin-transform-react-jsx-source/-/plugin-transform-react-jsx-source-7.27.1.tgz";
    hash = "sha512-zbwoTsBruTeKB9hSq73ha66iFeJHuaFkUbwvqElnygoNbj/jHRsSeokowZFN3CZ64IvEqcmmkVe89OPXc7ldAw==";
    name = "plugin-transform-react-jsx-source-7.27.1.tgz";
  };
  "@babel/runtime@7.28.4" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/runtime/-/runtime-7.28.4.tgz";
    hash = "sha512-Q/N6JNWvIvPnLDvjlE1OUBLPQHH6l3CltCEsHIujp45zQUSSh8K+gHnaEX45yAT1nyngnINhvWtzN+Nb9D8RAQ==";
    name = "runtime-7.28.4.tgz";
  };
  "@babel/template@7.27.2" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/template/-/template-7.27.2.tgz";
    hash = "sha512-LPDZ85aEJyYSd18/DkjNh4/y1ntkE5KwUHWTiqgRxruuZL2F1yuHligVHLvcHY2vMHXttKFpJn6LwfI7cw7ODw==";
    name = "template-7.27.2.tgz";
  };
  "@babel/traverse@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/traverse/-/traverse-7.28.5.tgz";
    hash = "sha512-TCCj4t55U90khlYkVV/0TfkJkAkUg3jZFA3Neb7unZT8CPok7iiRfaX0F+WnqWqt7OxhOn0uBKXCw4lbL8W0aQ==";
    name = "traverse-7.28.5.tgz";
  };
  "@babel/types@7.28.5" = fetchurl {
    url = "https://registry.npmmirror.com/@babel/types/-/types-7.28.5.tgz";
    hash = "sha512-qQ5m48eI/MFLQ5PxQj4PFaprjyCTLI37ElWMmNs0K8Lk3dVeOdNpB3ks8jc7yM5CDmVC73eMVk/trk3fgmrUpA==";
    name = "types-7.28.5.tgz";
  };
  "@emnapi/core@1.6.0" = fetchurl {
    url = "https://registry.npmmirror.com/@emnapi/core/-/core-1.6.0.tgz";
    hash = "sha512-zq/ay+9fNIJJtJiZxdTnXS20PllcYMX3OE23ESc4HK/bdYu3cOWYVhsOhVnXALfU/uqJIxn5NBPd9z4v+SfoSg==";
    name = "core-1.6.0.tgz";
  };
  "@emnapi/runtime@1.6.0" = fetchurl {
    url = "https://registry.npmmirror.com/@emnapi/runtime/-/runtime-1.6.0.tgz";
    hash = "sha512-obtUmAHTMjll499P+D9A3axeJFlhdjOWdKUNs/U6QIGT7V5RjcUW1xToAzjvmgTSQhDbYn/NwfTRoJcQ2rNBxA==";
    name = "runtime-1.6.0.tgz";
  };
  "@emnapi/wasi-threads@1.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/@emnapi/wasi-threads/-/wasi-threads-1.1.0.tgz";
    hash = "sha512-WI0DdZ8xFSbgMjR1sFsKABJ/C5OnRrjT06JXbZKexJGrDuPTzZdDYfFlsgcCXCyf+suG5QU2e/y1Wo2V/OapLQ==";
    name = "wasi-threads-1.1.0.tgz";
  };
  "@esbuild/aix-ppc64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/aix-ppc64/-/aix-ppc64-0.25.11.tgz";
    hash = "sha512-Xt1dOL13m8u0WE8iplx9Ibbm+hFAO0GsU2P34UNoDGvZYkY8ifSiy6Zuc1lYxfG7svWE2fzqCUmFp5HCn51gJg==";
    name = "aix-ppc64-0.25.11.tgz";
  };
  "@esbuild/android-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/android-arm64/-/android-arm64-0.25.11.tgz";
    hash = "sha512-9slpyFBc4FPPz48+f6jyiXOx/Y4v34TUeDDXJpZqAWQn/08lKGeD8aDp9TMn9jDz2CiEuHwfhRmGBvpnd/PWIQ==";
    name = "android-arm64-0.25.11.tgz";
  };
  "@esbuild/android-arm@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/android-arm/-/android-arm-0.25.11.tgz";
    hash = "sha512-uoa7dU+Dt3HYsethkJ1k6Z9YdcHjTrSb5NUy66ZfZaSV8hEYGD5ZHbEMXnqLFlbBflLsl89Zke7CAdDJ4JI+Gg==";
    name = "android-arm-0.25.11.tgz";
  };
  "@esbuild/android-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/android-x64/-/android-x64-0.25.11.tgz";
    hash = "sha512-Sgiab4xBjPU1QoPEIqS3Xx+R2lezu0LKIEcYe6pftr56PqPygbB7+szVnzoShbx64MUupqoE0KyRlN7gezbl8g==";
    name = "android-x64-0.25.11.tgz";
  };
  "@esbuild/darwin-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/darwin-arm64/-/darwin-arm64-0.25.11.tgz";
    hash = "sha512-VekY0PBCukppoQrycFxUqkCojnTQhdec0vevUL/EDOCnXd9LKWqD/bHwMPzigIJXPhC59Vd1WFIL57SKs2mg4w==";
    name = "darwin-arm64-0.25.11.tgz";
  };
  "@esbuild/darwin-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/darwin-x64/-/darwin-x64-0.25.11.tgz";
    hash = "sha512-+hfp3yfBalNEpTGp9loYgbknjR695HkqtY3d3/JjSRUyPg/xd6q+mQqIb5qdywnDxRZykIHs3axEqU6l1+oWEQ==";
    name = "darwin-x64-0.25.11.tgz";
  };
  "@esbuild/freebsd-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/freebsd-arm64/-/freebsd-arm64-0.25.11.tgz";
    hash = "sha512-CmKjrnayyTJF2eVuO//uSjl/K3KsMIeYeyN7FyDBjsR3lnSJHaXlVoAK8DZa7lXWChbuOk7NjAc7ygAwrnPBhA==";
    name = "freebsd-arm64-0.25.11.tgz";
  };
  "@esbuild/freebsd-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/freebsd-x64/-/freebsd-x64-0.25.11.tgz";
    hash = "sha512-Dyq+5oscTJvMaYPvW3x3FLpi2+gSZTCE/1ffdwuM6G1ARang/mb3jvjxs0mw6n3Lsw84ocfo9CrNMqc5lTfGOw==";
    name = "freebsd-x64-0.25.11.tgz";
  };
  "@esbuild/linux-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-arm64/-/linux-arm64-0.25.11.tgz";
    hash = "sha512-Qr8AzcplUhGvdyUF08A1kHU3Vr2O88xxP0Tm8GcdVOUm25XYcMPp2YqSVHbLuXzYQMf9Bh/iKx7YPqECs6ffLA==";
    name = "linux-arm64-0.25.11.tgz";
  };
  "@esbuild/linux-arm@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-arm/-/linux-arm-0.25.11.tgz";
    hash = "sha512-TBMv6B4kCfrGJ8cUPo7vd6NECZH/8hPpBHHlYI3qzoYFvWu2AdTvZNuU/7hsbKWqu/COU7NIK12dHAAqBLLXgw==";
    name = "linux-arm-0.25.11.tgz";
  };
  "@esbuild/linux-ia32@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-ia32/-/linux-ia32-0.25.11.tgz";
    hash = "sha512-TmnJg8BMGPehs5JKrCLqyWTVAvielc615jbkOirATQvWWB1NMXY77oLMzsUjRLa0+ngecEmDGqt5jiDC6bfvOw==";
    name = "linux-ia32-0.25.11.tgz";
  };
  "@esbuild/linux-loong64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-loong64/-/linux-loong64-0.25.11.tgz";
    hash = "sha512-DIGXL2+gvDaXlaq8xruNXUJdT5tF+SBbJQKbWy/0J7OhU8gOHOzKmGIlfTTl6nHaCOoipxQbuJi7O++ldrxgMw==";
    name = "linux-loong64-0.25.11.tgz";
  };
  "@esbuild/linux-mips64el@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-mips64el/-/linux-mips64el-0.25.11.tgz";
    hash = "sha512-Osx1nALUJu4pU43o9OyjSCXokFkFbyzjXb6VhGIJZQ5JZi8ylCQ9/LFagolPsHtgw6himDSyb5ETSfmp4rpiKQ==";
    name = "linux-mips64el-0.25.11.tgz";
  };
  "@esbuild/linux-ppc64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-ppc64/-/linux-ppc64-0.25.11.tgz";
    hash = "sha512-nbLFgsQQEsBa8XSgSTSlrnBSrpoWh7ioFDUmwo158gIm5NNP+17IYmNWzaIzWmgCxq56vfr34xGkOcZ7jX6CPw==";
    name = "linux-ppc64-0.25.11.tgz";
  };
  "@esbuild/linux-riscv64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-riscv64/-/linux-riscv64-0.25.11.tgz";
    hash = "sha512-HfyAmqZi9uBAbgKYP1yGuI7tSREXwIb438q0nqvlpxAOs3XnZ8RsisRfmVsgV486NdjD7Mw2UrFSw51lzUk1ww==";
    name = "linux-riscv64-0.25.11.tgz";
  };
  "@esbuild/linux-s390x@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-s390x/-/linux-s390x-0.25.11.tgz";
    hash = "sha512-HjLqVgSSYnVXRisyfmzsH6mXqyvj0SA7pG5g+9W7ESgwA70AXYNpfKBqh1KbTxmQVaYxpzA/SvlB9oclGPbApw==";
    name = "linux-s390x-0.25.11.tgz";
  };
  "@esbuild/linux-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/linux-x64/-/linux-x64-0.25.11.tgz";
    hash = "sha512-HSFAT4+WYjIhrHxKBwGmOOSpphjYkcswF449j6EjsjbinTZbp8PJtjsVK1XFJStdzXdy/jaddAep2FGY+wyFAQ==";
    name = "linux-x64-0.25.11.tgz";
  };
  "@esbuild/netbsd-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/netbsd-arm64/-/netbsd-arm64-0.25.11.tgz";
    hash = "sha512-hr9Oxj1Fa4r04dNpWr3P8QKVVsjQhqrMSUzZzf+LZcYjZNqhA3IAfPQdEh1FLVUJSiu6sgAwp3OmwBfbFgG2Xg==";
    name = "netbsd-arm64-0.25.11.tgz";
  };
  "@esbuild/netbsd-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/netbsd-x64/-/netbsd-x64-0.25.11.tgz";
    hash = "sha512-u7tKA+qbzBydyj0vgpu+5h5AeudxOAGncb8N6C9Kh1N4n7wU1Xw1JDApsRjpShRpXRQlJLb9wY28ELpwdPcZ7A==";
    name = "netbsd-x64-0.25.11.tgz";
  };
  "@esbuild/openbsd-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/openbsd-arm64/-/openbsd-arm64-0.25.11.tgz";
    hash = "sha512-Qq6YHhayieor3DxFOoYM1q0q1uMFYb7cSpLD2qzDSvK1NAvqFi8Xgivv0cFC6J+hWVw2teCYltyy9/m/14ryHg==";
    name = "openbsd-arm64-0.25.11.tgz";
  };
  "@esbuild/openbsd-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/openbsd-x64/-/openbsd-x64-0.25.11.tgz";
    hash = "sha512-CN+7c++kkbrckTOz5hrehxWN7uIhFFlmS/hqziSFVWpAzpWrQoAG4chH+nN3Be+Kzv/uuo7zhX716x3Sn2Jduw==";
    name = "openbsd-x64-0.25.11.tgz";
  };
  "@esbuild/openharmony-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/openharmony-arm64/-/openharmony-arm64-0.25.11.tgz";
    hash = "sha512-rOREuNIQgaiR+9QuNkbkxubbp8MSO9rONmwP5nKncnWJ9v5jQ4JxFnLu4zDSRPf3x4u+2VN4pM4RdyIzDty/wQ==";
    name = "openharmony-arm64-0.25.11.tgz";
  };
  "@esbuild/sunos-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/sunos-x64/-/sunos-x64-0.25.11.tgz";
    hash = "sha512-nq2xdYaWxyg9DcIyXkZhcYulC6pQ2FuCgem3LI92IwMgIZ69KHeY8T4Y88pcwoLIjbed8n36CyKoYRDygNSGhA==";
    name = "sunos-x64-0.25.11.tgz";
  };
  "@esbuild/win32-arm64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/win32-arm64/-/win32-arm64-0.25.11.tgz";
    hash = "sha512-3XxECOWJq1qMZ3MN8srCJ/QfoLpL+VaxD/WfNRm1O3B4+AZ/BnLVgFbUV3eiRYDMXetciH16dwPbbHqwe1uU0Q==";
    name = "win32-arm64-0.25.11.tgz";
  };
  "@esbuild/win32-ia32@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/win32-ia32/-/win32-ia32-0.25.11.tgz";
    hash = "sha512-3ukss6gb9XZ8TlRyJlgLn17ecsK4NSQTmdIXRASVsiS2sQ6zPPZklNJT5GR5tE/MUarymmy8kCEf5xPCNCqVOA==";
    name = "win32-ia32-0.25.11.tgz";
  };
  "@esbuild/win32-x64@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/@esbuild/win32-x64/-/win32-x64-0.25.11.tgz";
    hash = "sha512-D7Hpz6A2L4hzsRpPaCYkQnGOotdUpDzSGRIv9I+1ITdHROSFUWW95ZPZWQmGka1Fg7W3zFJowyn9WGwMJ0+KPA==";
    name = "win32-x64-0.25.11.tgz";
  };
  "@eslint-community/eslint-utils@4.9.0" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint-community/eslint-utils/-/eslint-utils-4.9.0.tgz";
    hash = "sha512-ayVFHdtZ+hsq1t2Dy24wCmGXGe4q9Gu3smhLYALJrr473ZH27MsnSL+LKUlimp4BWJqMDMLmPpx/Q9R3OAlL4g==";
    name = "eslint-utils-4.9.0.tgz";
  };
  "@eslint-community/regexpp@4.12.2" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint-community/regexpp/-/regexpp-4.12.2.tgz";
    hash = "sha512-EriSTlt5OC9/7SXkRSCAhfSxxoSUgBm33OH+IkwbdpgoqsSsUg7y3uh+IICI/Qg4BBWr3U2i39RpmycbxMq4ew==";
    name = "regexpp-4.12.2.tgz";
  };
  "@eslint/config-array@0.21.1" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/config-array/-/config-array-0.21.1.tgz";
    hash = "sha512-aw1gNayWpdI/jSYVgzN5pL0cfzU02GT3NBpeT/DXbx1/1x7ZKxFPd9bwrzygx/qiwIQiJ1sw/zD8qY/kRvlGHA==";
    name = "config-array-0.21.1.tgz";
  };
  "@eslint/config-helpers@0.4.2" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/config-helpers/-/config-helpers-0.4.2.tgz";
    hash = "sha512-gBrxN88gOIf3R7ja5K9slwNayVcZgK6SOUORm2uBzTeIEfeVaIhOpCtTox3P6R7o2jLFwLFTLnC7kU/RGcYEgw==";
    name = "config-helpers-0.4.2.tgz";
  };
  "@eslint/core@0.17.0" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/core/-/core-0.17.0.tgz";
    hash = "sha512-yL/sLrpmtDaFEiUj1osRP4TI2MDz1AddJL+jZ7KSqvBuliN4xqYY54IfdN8qD8Toa6g1iloph1fxQNkjOxrrpQ==";
    name = "core-0.17.0.tgz";
  };
  "@eslint/eslintrc@3.3.3" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/eslintrc/-/eslintrc-3.3.3.tgz";
    hash = "sha512-Kr+LPIUVKz2qkx1HAMH8q1q6azbqBAsXJUxBl/ODDuVPX45Z9DfwB8tPjTi6nNZ8BuM3nbJxC5zCAg5elnBUTQ==";
    name = "eslintrc-3.3.3.tgz";
  };
  "@eslint/js@9.39.1" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/js/-/js-9.39.1.tgz";
    hash = "sha512-S26Stp4zCy88tH94QbBv3XCuzRQiZ9yXofEILmglYTh/Ug/a9/umqvgFtYBAo3Lp0nsI/5/qH1CCrbdK3AP1Tw==";
    name = "js-9.39.1.tgz";
  };
  "@eslint/object-schema@2.1.7" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/object-schema/-/object-schema-2.1.7.tgz";
    hash = "sha512-VtAOaymWVfZcmZbp6E2mympDIHvyjXs/12LqWYjVw6qjrfF+VK+fyG33kChz3nnK+SU5/NeHOqrTEHS8sXO3OA==";
    name = "object-schema-2.1.7.tgz";
  };
  "@eslint/plugin-kit@0.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/@eslint/plugin-kit/-/plugin-kit-0.4.1.tgz";
    hash = "sha512-43/qtrDUokr7LJqoF2c3+RInu/t4zfrpYdoSDfYyhg52rwLV6TnOvdG4fXm7IkSB3wErkcmJS9iEhjVtOSEjjA==";
    name = "plugin-kit-0.4.1.tgz";
  };
  "@humanfs/core@0.19.1" = fetchurl {
    url = "https://registry.npmmirror.com/@humanfs/core/-/core-0.19.1.tgz";
    hash = "sha512-5DyQ4+1JEUzejeK1JGICcideyfUbGixgS9jNgex5nqkW+cY7WZhxBigmieN5Qnw9ZosSNVC9KQKyb+GUaGyKUA==";
    name = "core-0.19.1.tgz";
  };
  "@humanfs/node@0.16.7" = fetchurl {
    url = "https://registry.npmmirror.com/@humanfs/node/-/node-0.16.7.tgz";
    hash = "sha512-/zUx+yOsIrG4Y43Eh2peDeKCxlRt/gET6aHfaKpuq267qXdYDFViVHfMaLyygZOnl0kGWxFIgsBy8QFuTLUXEQ==";
    name = "node-0.16.7.tgz";
  };
  "@humanwhocodes/module-importer@1.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/@humanwhocodes/module-importer/-/module-importer-1.0.1.tgz";
    hash = "sha512-bxveV4V8v5Yb4ncFTT3rPSgZBOpCkjfK0y4oVVVJwIuDVBRMDXrPyXRL988i5ap9m9bnyEEjWfm5WkBmtffLfA==";
    name = "module-importer-1.0.1.tgz";
  };
  "@humanwhocodes/retry@0.4.3" = fetchurl {
    url = "https://registry.npmmirror.com/@humanwhocodes/retry/-/retry-0.4.3.tgz";
    hash = "sha512-bV0Tgo9K4hfPCek+aMAn81RppFKv2ySDQeMoSZuvTASywNTnVJCArCZE2FWqpvIatKu7VMRLWlR1EazvVhDyhQ==";
    name = "retry-0.4.3.tgz";
  };
  "@jridgewell/gen-mapping@0.3.13" = fetchurl {
    url = "https://registry.npmmirror.com/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
    hash = "sha512-2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
    name = "gen-mapping-0.3.13.tgz";
  };
  "@jridgewell/remapping@2.3.5" = fetchurl {
    url = "https://registry.npmmirror.com/@jridgewell/remapping/-/remapping-2.3.5.tgz";
    hash = "sha512-LI9u/+laYG4Ds1TDKSJW2YPrIlcVYOwi2fUC6xB43lueCjgxV4lffOCZCtYFiH6TNOX+tQKXx97T4IKHbhyHEQ==";
    name = "remapping-2.3.5.tgz";
  };
  "@jridgewell/resolve-uri@3.1.2" = fetchurl {
    url = "https://registry.npmmirror.com/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
    hash = "sha512-bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
    name = "resolve-uri-3.1.2.tgz";
  };
  "@jridgewell/sourcemap-codec@1.5.5" = fetchurl {
    url = "https://registry.npmmirror.com/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
    hash = "sha512-cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
    name = "sourcemap-codec-1.5.5.tgz";
  };
  "@jridgewell/trace-mapping@0.3.31" = fetchurl {
    url = "https://registry.npmmirror.com/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
    hash = "sha512-zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
    name = "trace-mapping-0.3.31.tgz";
  };
  "@napi-rs/wasm-runtime@1.0.7" = fetchurl {
    url = "https://registry.npmmirror.com/@napi-rs/wasm-runtime/-/wasm-runtime-1.0.7.tgz";
    hash = "sha512-SeDnOO0Tk7Okiq6DbXmmBODgOAb9dp9gjlphokTUxmt8U3liIP1ZsozBahH69j/RJv+Rfs6IwUKHTgQYJ/HBAw==";
    name = "wasm-runtime-1.0.7.tgz";
  };
  "@playwright/test@1.58.0" = fetchurl {
    url = "https://registry.npmmirror.com/@playwright/test/-/test-1.58.0.tgz";
    hash = "sha512-fWza+Lpbj6SkQKCrU6si4iu+fD2dD3gxNHFhUPxsfXBPhnv3rRSQVd0NtBUT9Z/RhF/boCBcuUaMUSTRTopjZg==";
    name = "test-1.58.0.tgz";
  };
  "@rolldown/pluginutils@1.0.0-beta.27" = fetchurl {
    url = "https://registry.npmmirror.com/@rolldown/pluginutils/-/pluginutils-1.0.0-beta.27.tgz";
    hash = "sha512-+d0F4MKMCbeVUJwG96uQ4SgAznZNSq93I3V+9NHA4OpvqG8mRCpGdKmK8l/dl02h2CCDHwW2FqilnTyDcAnqjA==";
    name = "pluginutils-1.0.0-beta.27.tgz";
  };
  "@rollup/rollup-android-arm-eabi@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-android-arm-eabi/-/rollup-android-arm-eabi-4.52.5.tgz";
    hash = "sha512-8c1vW4ocv3UOMp9K+gToY5zL2XiiVw3k7f1ksf4yO1FlDFQ1C2u72iACFnSOceJFsWskc2WZNqeRhFRPzv+wtQ==";
    name = "rollup-android-arm-eabi-4.52.5.tgz";
  };
  "@rollup/rollup-android-arm64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-android-arm64/-/rollup-android-arm64-4.52.5.tgz";
    hash = "sha512-mQGfsIEFcu21mvqkEKKu2dYmtuSZOBMmAl5CFlPGLY94Vlcm+zWApK7F/eocsNzp8tKmbeBP8yXyAbx0XHsFNA==";
    name = "rollup-android-arm64-4.52.5.tgz";
  };
  "@rollup/rollup-darwin-arm64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-darwin-arm64/-/rollup-darwin-arm64-4.52.5.tgz";
    hash = "sha512-takF3CR71mCAGA+v794QUZ0b6ZSrgJkArC+gUiG6LB6TQty9T0Mqh3m2ImRBOxS2IeYBo4lKWIieSvnEk2OQWA==";
    name = "rollup-darwin-arm64-4.52.5.tgz";
  };
  "@rollup/rollup-darwin-x64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-darwin-x64/-/rollup-darwin-x64-4.52.5.tgz";
    hash = "sha512-W901Pla8Ya95WpxDn//VF9K9u2JbocwV/v75TE0YIHNTbhqUTv9w4VuQ9MaWlNOkkEfFwkdNhXgcLqPSmHy0fA==";
    name = "rollup-darwin-x64-4.52.5.tgz";
  };
  "@rollup/rollup-freebsd-arm64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-freebsd-arm64/-/rollup-freebsd-arm64-4.52.5.tgz";
    hash = "sha512-QofO7i7JycsYOWxe0GFqhLmF6l1TqBswJMvICnRUjqCx8b47MTo46W8AoeQwiokAx3zVryVnxtBMcGcnX12LvA==";
    name = "rollup-freebsd-arm64-4.52.5.tgz";
  };
  "@rollup/rollup-freebsd-x64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-freebsd-x64/-/rollup-freebsd-x64-4.52.5.tgz";
    hash = "sha512-jr21b/99ew8ujZubPo9skbrItHEIE50WdV86cdSoRkKtmWa+DDr6fu2c/xyRT0F/WazZpam6kk7IHBerSL7LDQ==";
    name = "rollup-freebsd-x64-4.52.5.tgz";
  };
  "@rollup/rollup-linux-arm-gnueabihf@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-arm-gnueabihf/-/rollup-linux-arm-gnueabihf-4.52.5.tgz";
    hash = "sha512-PsNAbcyv9CcecAUagQefwX8fQn9LQ4nZkpDboBOttmyffnInRy8R8dSg6hxxl2Re5QhHBf6FYIDhIj5v982ATQ==";
    name = "rollup-linux-arm-gnueabihf-4.52.5.tgz";
  };
  "@rollup/rollup-linux-arm-musleabihf@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-arm-musleabihf/-/rollup-linux-arm-musleabihf-4.52.5.tgz";
    hash = "sha512-Fw4tysRutyQc/wwkmcyoqFtJhh0u31K+Q6jYjeicsGJJ7bbEq8LwPWV/w0cnzOqR2m694/Af6hpFayLJZkG2VQ==";
    name = "rollup-linux-arm-musleabihf-4.52.5.tgz";
  };
  "@rollup/rollup-linux-arm64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-arm64-gnu/-/rollup-linux-arm64-gnu-4.52.5.tgz";
    hash = "sha512-a+3wVnAYdQClOTlyapKmyI6BLPAFYs0JM8HRpgYZQO02rMR09ZcV9LbQB+NL6sljzG38869YqThrRnfPMCDtZg==";
    name = "rollup-linux-arm64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-arm64-musl@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-arm64-musl/-/rollup-linux-arm64-musl-4.52.5.tgz";
    hash = "sha512-AvttBOMwO9Pcuuf7m9PkC1PUIKsfaAJ4AYhy944qeTJgQOqJYJ9oVl2nYgY7Rk0mkbsuOpCAYSs6wLYB2Xiw0Q==";
    name = "rollup-linux-arm64-musl-4.52.5.tgz";
  };
  "@rollup/rollup-linux-loong64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-loong64-gnu/-/rollup-linux-loong64-gnu-4.52.5.tgz";
    hash = "sha512-DkDk8pmXQV2wVrF6oq5tONK6UHLz/XcEVow4JTTerdeV1uqPeHxwcg7aFsfnSm9L+OO8WJsWotKM2JJPMWrQtA==";
    name = "rollup-linux-loong64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-ppc64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-ppc64-gnu/-/rollup-linux-ppc64-gnu-4.52.5.tgz";
    hash = "sha512-W/b9ZN/U9+hPQVvlGwjzi+Wy4xdoH2I8EjaCkMvzpI7wJUs8sWJ03Rq96jRnHkSrcHTpQe8h5Tg3ZzUPGauvAw==";
    name = "rollup-linux-ppc64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-riscv64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-riscv64-gnu/-/rollup-linux-riscv64-gnu-4.52.5.tgz";
    hash = "sha512-sjQLr9BW7R/ZiXnQiWPkErNfLMkkWIoCz7YMn27HldKsADEKa5WYdobaa1hmN6slu9oWQbB6/jFpJ+P2IkVrmw==";
    name = "rollup-linux-riscv64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-riscv64-musl@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-riscv64-musl/-/rollup-linux-riscv64-musl-4.52.5.tgz";
    hash = "sha512-hq3jU/kGyjXWTvAh2awn8oHroCbrPm8JqM7RUpKjalIRWWXE01CQOf/tUNWNHjmbMHg/hmNCwc/Pz3k1T/j/Lg==";
    name = "rollup-linux-riscv64-musl-4.52.5.tgz";
  };
  "@rollup/rollup-linux-s390x-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-s390x-gnu/-/rollup-linux-s390x-gnu-4.52.5.tgz";
    hash = "sha512-gn8kHOrku8D4NGHMK1Y7NA7INQTRdVOntt1OCYypZPRt6skGbddska44K8iocdpxHTMMNui5oH4elPH4QOLrFQ==";
    name = "rollup-linux-s390x-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-x64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.52.5.tgz";
    hash = "sha512-hXGLYpdhiNElzN770+H2nlx+jRog8TyynpTVzdlc6bndktjKWyZyiCsuDAlpd+j+W+WNqfcyAWz9HxxIGfZm1Q==";
    name = "rollup-linux-x64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-linux-x64-musl@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-linux-x64-musl/-/rollup-linux-x64-musl-4.52.5.tgz";
    hash = "sha512-arCGIcuNKjBoKAXD+y7XomR9gY6Mw7HnFBv5Rw7wQRvwYLR7gBAgV7Mb2QTyjXfTveBNFAtPt46/36vV9STLNg==";
    name = "rollup-linux-x64-musl-4.52.5.tgz";
  };
  "@rollup/rollup-openharmony-arm64@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-openharmony-arm64/-/rollup-openharmony-arm64-4.52.5.tgz";
    hash = "sha512-QoFqB6+/9Rly/RiPjaomPLmR/13cgkIGfA40LHly9zcH1S0bN2HVFYk3a1eAyHQyjs3ZJYlXvIGtcCs5tko9Cw==";
    name = "rollup-openharmony-arm64-4.52.5.tgz";
  };
  "@rollup/rollup-win32-arm64-msvc@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-win32-arm64-msvc/-/rollup-win32-arm64-msvc-4.52.5.tgz";
    hash = "sha512-w0cDWVR6MlTstla1cIfOGyl8+qb93FlAVutcor14Gf5Md5ap5ySfQ7R9S/NjNaMLSFdUnKGEasmVnu3lCMqB7w==";
    name = "rollup-win32-arm64-msvc-4.52.5.tgz";
  };
  "@rollup/rollup-win32-ia32-msvc@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-win32-ia32-msvc/-/rollup-win32-ia32-msvc-4.52.5.tgz";
    hash = "sha512-Aufdpzp7DpOTULJCuvzqcItSGDH73pF3ko/f+ckJhxQyHtp67rHw3HMNxoIdDMUITJESNE6a8uh4Lo4SLouOUg==";
    name = "rollup-win32-ia32-msvc-4.52.5.tgz";
  };
  "@rollup/rollup-win32-x64-gnu@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-win32-x64-gnu/-/rollup-win32-x64-gnu-4.52.5.tgz";
    hash = "sha512-UGBUGPFp1vkj6p8wCRraqNhqwX/4kNQPS57BCFc8wYh0g94iVIW33wJtQAx3G7vrjjNtRaxiMUylM0ktp/TRSQ==";
    name = "rollup-win32-x64-gnu-4.52.5.tgz";
  };
  "@rollup/rollup-win32-x64-msvc@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/@rollup/rollup-win32-x64-msvc/-/rollup-win32-x64-msvc-4.52.5.tgz";
    hash = "sha512-TAcgQh2sSkykPRWLrdyy2AiceMckNf5loITqXxFI5VuQjS5tSuw3WlwdN8qv8vzjLAUTvYaH/mVjSFpbkFbpTg==";
    name = "rollup-win32-x64-msvc-4.52.5.tgz";
  };
  "@tailwindcss/node@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/node/-/node-4.1.16.tgz";
    hash = "sha512-BX5iaSsloNuvKNHRN3k2RcCuTEgASTo77mofW0vmeHkfrDWaoFAFvNHpEgtu0eqyypcyiBkDWzSMxJhp3AUVcw==";
    name = "node-4.1.16.tgz";
  };
  "@tailwindcss/oxide-android-arm64@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-android-arm64/-/oxide-android-arm64-4.1.16.tgz";
    hash = "sha512-8+ctzkjHgwDJ5caq9IqRSgsP70xhdhJvm+oueS/yhD5ixLhqTw9fSL1OurzMUhBwE5zK26FXLCz2f/RtkISqHA==";
    name = "oxide-android-arm64-4.1.16.tgz";
  };
  "@tailwindcss/oxide-darwin-arm64@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-darwin-arm64/-/oxide-darwin-arm64-4.1.16.tgz";
    hash = "sha512-C3oZy5042v2FOALBZtY0JTDnGNdS6w7DxL/odvSny17ORUnaRKhyTse8xYi3yKGyfnTUOdavRCdmc8QqJYwFKA==";
    name = "oxide-darwin-arm64-4.1.16.tgz";
  };
  "@tailwindcss/oxide-darwin-x64@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-darwin-x64/-/oxide-darwin-x64-4.1.16.tgz";
    hash = "sha512-vjrl/1Ub9+JwU6BP0emgipGjowzYZMjbWCDqwA2Z4vCa+HBSpP4v6U2ddejcHsolsYxwL5r4bPNoamlV0xDdLg==";
    name = "oxide-darwin-x64-4.1.16.tgz";
  };
  "@tailwindcss/oxide-freebsd-x64@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-freebsd-x64/-/oxide-freebsd-x64-4.1.16.tgz";
    hash = "sha512-TSMpPYpQLm+aR1wW5rKuUuEruc/oOX3C7H0BTnPDn7W/eMw8W+MRMpiypKMkXZfwH8wqPIRKppuZoedTtNj2tg==";
    name = "oxide-freebsd-x64-4.1.16.tgz";
  };
  "@tailwindcss/oxide-linux-arm-gnueabihf@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-linux-arm-gnueabihf/-/oxide-linux-arm-gnueabihf-4.1.16.tgz";
    hash = "sha512-p0GGfRg/w0sdsFKBjMYvvKIiKy/LNWLWgV/plR4lUgrsxFAoQBFrXkZ4C0w8IOXfslB9vHK/JGASWD2IefIpvw==";
    name = "oxide-linux-arm-gnueabihf-4.1.16.tgz";
  };
  "@tailwindcss/oxide-linux-arm64-gnu@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-linux-arm64-gnu/-/oxide-linux-arm64-gnu-4.1.16.tgz";
    hash = "sha512-DoixyMmTNO19rwRPdqviTrG1rYzpxgyYJl8RgQvdAQUzxC1ToLRqtNJpU/ATURSKgIg6uerPw2feW0aS8SNr/w==";
    name = "oxide-linux-arm64-gnu-4.1.16.tgz";
  };
  "@tailwindcss/oxide-linux-arm64-musl@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-linux-arm64-musl/-/oxide-linux-arm64-musl-4.1.16.tgz";
    hash = "sha512-H81UXMa9hJhWhaAUca6bU2wm5RRFpuHImrwXBUvPbYb+3jo32I9VIwpOX6hms0fPmA6f2pGVlybO6qU8pF4fzQ==";
    name = "oxide-linux-arm64-musl-4.1.16.tgz";
  };
  "@tailwindcss/oxide-linux-x64-gnu@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-linux-x64-gnu/-/oxide-linux-x64-gnu-4.1.16.tgz";
    hash = "sha512-ZGHQxDtFC2/ruo7t99Qo2TTIvOERULPl5l0K1g0oK6b5PGqjYMga+FcY1wIUnrUxY56h28FxybtDEla+ICOyew==";
    name = "oxide-linux-x64-gnu-4.1.16.tgz";
  };
  "@tailwindcss/oxide-linux-x64-musl@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-linux-x64-musl/-/oxide-linux-x64-musl-4.1.16.tgz";
    hash = "sha512-Oi1tAaa0rcKf1Og9MzKeINZzMLPbhxvm7rno5/zuP1WYmpiG0bEHq4AcRUiG2165/WUzvxkW4XDYCscZWbTLZw==";
    name = "oxide-linux-x64-musl-4.1.16.tgz";
  };
  "@tailwindcss/oxide-wasm32-wasi@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-wasm32-wasi/-/oxide-wasm32-wasi-4.1.16.tgz";
    hash = "sha512-B01u/b8LteGRwucIBmCQ07FVXLzImWESAIMcUU6nvFt/tYsQ6IHz8DmZ5KtvmwxD+iTYBtM1xwoGXswnlu9v0Q==";
    name = "oxide-wasm32-wasi-4.1.16.tgz";
  };
  "@tailwindcss/oxide-win32-arm64-msvc@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-win32-arm64-msvc/-/oxide-win32-arm64-msvc-4.1.16.tgz";
    hash = "sha512-zX+Q8sSkGj6HKRTMJXuPvOcP8XfYON24zJBRPlszcH1Np7xuHXhWn8qfFjIujVzvH3BHU+16jBXwgpl20i+v9A==";
    name = "oxide-win32-arm64-msvc-4.1.16.tgz";
  };
  "@tailwindcss/oxide-win32-x64-msvc@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide-win32-x64-msvc/-/oxide-win32-x64-msvc-4.1.16.tgz";
    hash = "sha512-m5dDFJUEejbFqP+UXVstd4W/wnxA4F61q8SoL+mqTypId2T2ZpuxosNSgowiCnLp2+Z+rivdU0AqpfgiD7yCBg==";
    name = "oxide-win32-x64-msvc-4.1.16.tgz";
  };
  "@tailwindcss/oxide@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/oxide/-/oxide-4.1.16.tgz";
    hash = "sha512-2OSv52FRuhdlgyOQqgtQHuCgXnS8nFSYRp2tJ+4WZXKgTxqPy7SMSls8c3mPT5pkZ17SBToGM5LHEJBO7miEdg==";
    name = "oxide-4.1.16.tgz";
  };
  "@tailwindcss/vite@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/@tailwindcss/vite/-/vite-4.1.16.tgz";
    hash = "sha512-bbguNBcDxsRmi9nnlWJxhfDWamY3lmcyACHcdO1crxfzuLpOhHLLtEIN/nCbbAtj5rchUgQD17QVAKi1f7IsKg==";
    name = "vite-4.1.16.tgz";
  };
  "@tauri-apps/api@2.10.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/api/-/api-2.10.1.tgz";
    hash = "sha512-hKL/jWf293UDSUN09rR69hrToyIXBb8CjGaWC7gfinvnQrBVvnLr08FeFi38gxtugAVyVcTa5/FD/Xnkb1siBw==";
    name = "api-2.10.1.tgz";
  };
  "@tauri-apps/api@2.11.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/api/-/api-2.11.1.tgz";
    hash = "sha512-M2FPuYND2m+wh5hfW9ZpSdxMPdEJovPBWwoHJmwUpysTYNHaOkVFN419m/K0LIgjb/7KU2vBgsUepJWugQCvAA==";
    name = "api-2.11.1.tgz";
  };
  "@tauri-apps/api@2.9.0" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/api/-/api-2.9.0.tgz";
    hash = "sha512-qD5tMjh7utwBk9/5PrTA/aGr3i5QaJ/Mlt7p8NilQ45WgbifUNPyKWsA63iQ8YfQq6R8ajMapU+/Q8nMcPRLNw==";
    name = "api-2.9.0.tgz";
  };
  "@tauri-apps/cli-darwin-arm64@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-darwin-arm64/-/cli-darwin-arm64-2.11.4.tgz";
    hash = "sha512-1ryOF3ZhpZ/nemHV5zVwBQBz9jDGKmKPvWPADOhc83ig0P4bMc2iER4NbC6r9sjeIZ6RVQ4g3RZIYvezhcl4TQ==";
    name = "cli-darwin-arm64-2.11.4.tgz";
  };
  "@tauri-apps/cli-darwin-x64@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-darwin-x64/-/cli-darwin-x64-2.11.4.tgz";
    hash = "sha512-uFsGQAAfuyz1k/yGLmkWfkBlgKAqZfxqlHmLWx81QU27RJWfmbNHCIq8T8w1e+VClleIuZUjpHWfoE4E3DLo3A==";
    name = "cli-darwin-x64-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-arm-gnueabihf@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-arm-gnueabihf/-/cli-linux-arm-gnueabihf-2.11.4.tgz";
    hash = "sha512-IaHZn5CdBL21oUmjiVOS1ctw6Ip1O0pjp70FwOWmYz1myWe0SY96ZIj2FYf7pT0m8bI2h/hrs5ZbEXXh44/MkQ==";
    name = "cli-linux-arm-gnueabihf-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-arm64-gnu@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-arm64-gnu/-/cli-linux-arm64-gnu-2.11.4.tgz";
    hash = "sha512-N41/ukTRVe6XSuUTESuFdGeOW2i7k62tK+6gHK5Kd5/q5RPvvi19GaWAVPPb9u95HSGmTChSolBfzynUsssFaA==";
    name = "cli-linux-arm64-gnu-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-arm64-musl@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-arm64-musl/-/cli-linux-arm64-musl-2.11.4.tgz";
    hash = "sha512-v277UnT/fB64xAfSroL5N3Km3tLmvATWqJJw/wRI+g6o+HkeD0slyE7gOhNs1MbjE41R7bQOTxMVoL3aomUJmw==";
    name = "cli-linux-arm64-musl-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-riscv64-gnu@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-riscv64-gnu/-/cli-linux-riscv64-gnu-2.11.4.tgz";
    hash = "sha512-qqgNkQ2u1yZHxjhxsZaxUtRDW8dIqIYm33rx/mzwQv0SfY9x1B+iraj8vWeFiXjjSVVhEMepXSOts1TqPzvXNQ==";
    name = "cli-linux-riscv64-gnu-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-x64-gnu@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-x64-gnu/-/cli-linux-x64-gnu-2.11.4.tgz";
    hash = "sha512-2VRNWl84FOH0m2giiDkO2h0QXlcMJeX+zJDpI5kDIQAx6s+geF3v48F4DXfJez4GS/FdoDGnPnw1C2iYGbQ7bQ==";
    name = "cli-linux-x64-gnu-2.11.4.tgz";
  };
  "@tauri-apps/cli-linux-x64-musl@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-linux-x64-musl/-/cli-linux-x64-musl-2.11.4.tgz";
    hash = "sha512-o9GyhYor/nc7xarmwDE3ka2szuW3uuZzXjHWh64Q8YX5AtSgxdQkFWzrY4O8KiGtVNvFBI14H3Q49Qj5TOIP/A==";
    name = "cli-linux-x64-musl-2.11.4.tgz";
  };
  "@tauri-apps/cli-win32-arm64-msvc@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-win32-arm64-msvc/-/cli-win32-arm64-msvc-2.11.4.tgz";
    hash = "sha512-ld5Ehb598m0VkYyylRPNeCFsBe/km0jxis6KgMpl3IGY6I/i1RwQXO05I1AsXUXO2WC6AvB/Lw4qTf/asiuEiQ==";
    name = "cli-win32-arm64-msvc-2.11.4.tgz";
  };
  "@tauri-apps/cli-win32-ia32-msvc@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-win32-ia32-msvc/-/cli-win32-ia32-msvc-2.11.4.tgz";
    hash = "sha512-12Hxi0XX/H5VFxO/bGgHkFWhml9VMgEOu9CidjeCeTNQ1l6fpUlbiGgSP7CLI3PFtW9/FfbeHieZ+kyWK5H7CA==";
    name = "cli-win32-ia32-msvc-2.11.4.tgz";
  };
  "@tauri-apps/cli-win32-x64-msvc@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli-win32-x64-msvc/-/cli-win32-x64-msvc-2.11.4.tgz";
    hash = "sha512-+vDiqBIU5dMISg/wNvX3sF+ZHfgJGJ5T0AcO+EHNXV9GGAG+P5fzodlDXD3QdKCRgZxMoCm5PPvj3BqLNjBthw==";
    name = "cli-win32-x64-msvc-2.11.4.tgz";
  };
  "@tauri-apps/cli@2.11.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/cli/-/cli-2.11.4.tgz";
    hash = "sha512-R8xGtMpwyetawSqm9kYOuMmEqkhUbvcUy8n0aNXIxollKBLESUu5f4Fx+64hgASYm1H+jSWq6jCW6zqTnH6hqQ==";
    name = "cli-2.11.4.tgz";
  };
  "@tauri-apps/plugin-autostart@2.5.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-autostart/-/plugin-autostart-2.5.1.tgz";
    hash = "sha512-zS/xx7yzveCcotkA+8TqkI2lysmG2wvQXv2HGAVExITmnFfHAdj1arGsbbfs3o6EktRHf6l34pJxc3YGG2mg7w==";
    name = "plugin-autostart-2.5.1.tgz";
  };
  "@tauri-apps/plugin-clipboard-manager@2.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-clipboard-manager/-/plugin-clipboard-manager-2.3.2.tgz";
    hash = "sha512-CUlb5Hqi2oZbcZf4VUyUH53XWPPdtpw43EUpCza5HWZJwxEoDowFzNUDt1tRUXA8Uq+XPn17Ysfptip33sG4eQ==";
    name = "plugin-clipboard-manager-2.3.2.tgz";
  };
  "@tauri-apps/plugin-dialog@2.6.0" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-dialog/-/plugin-dialog-2.6.0.tgz";
    hash = "sha512-q4Uq3eY87TdcYzXACiYSPhmpBA76shgmQswGkSVio4C82Sz2W4iehe9TnKYwbq7weHiL88Yw19XZm7v28+Micg==";
    name = "plugin-dialog-2.6.0.tgz";
  };
  "@tauri-apps/plugin-fs@2.4.4" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-fs/-/plugin-fs-2.4.4.tgz";
    hash = "sha512-MTorXxIRmOnOPT1jZ3w96vjSuScER38ryXY88vl5F0uiKdnvTKKTtaEjTEo8uPbl4e3gnUtfsDVwC7h77GQLvQ==";
    name = "plugin-fs-2.4.4.tgz";
  };
  "@tauri-apps/plugin-global-shortcut@2.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-global-shortcut/-/plugin-global-shortcut-2.3.2.tgz";
    hash = "sha512-UReHNXrLvpEjylE4jb4oCYiy96uRykPUthoCQCmRXYrd5hs5X9DrW+qOn7GLW57EJN4tdK8bgK5twBTz2NOxzA==";
    name = "plugin-global-shortcut-2.3.2.tgz";
  };
  "@tauri-apps/plugin-opener@2.5.2" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-opener/-/plugin-opener-2.5.2.tgz";
    hash = "sha512-ei/yRRoCklWHImwpCcDK3VhNXx+QXM9793aQ64YxpqVF0BDuuIlXhZgiAkc15wnPVav+IbkYhmDJIv5R326Mew==";
    name = "plugin-opener-2.5.2.tgz";
  };
  "@tauri-apps/plugin-os@2.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-os/-/plugin-os-2.3.2.tgz";
    hash = "sha512-n+nXWeuSeF9wcEsSPmRnBEGrRgOy6jjkSU+UVCOV8YUGKb2erhDOxis7IqRXiRVHhY8XMKks00BJ0OAdkpf6+A==";
    name = "plugin-os-2.3.2.tgz";
  };
  "@tauri-apps/plugin-process@2.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-process/-/plugin-process-2.3.1.tgz";
    hash = "sha512-nCa4fGVaDL/B9ai03VyPOjfAHRHSBz5v6F/ObsB73r/dA3MHHhZtldaDMIc0V/pnUw9ehzr2iEG+XkSEyC0JJA==";
    name = "plugin-process-2.3.1.tgz";
  };
  "@tauri-apps/plugin-store@2.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tauri-apps/plugin-store/-/plugin-store-2.4.1.tgz";
    hash = "sha512-ckGSEzZ5Ii4Hf2D5x25Oqnm2Zf9MfDWAzR+volY0z/OOBz6aucPKEY0F649JvQ0Vupku6UJo7ugpGRDOFOunkA==";
    name = "plugin-store-2.4.1.tgz";
  };
  "@tybys/wasm-util@0.10.1" = fetchurl {
    url = "https://registry.npmmirror.com/@tybys/wasm-util/-/wasm-util-0.10.1.tgz";
    hash = "sha512-9tTaPJLSiejZKx+Bmog4uSubteqTvFrVrURwkmHixBo0G4seD0zUxp98E1DzUBJxLQ3NPwXrGKDiVjwx/DpPsg==";
    name = "wasm-util-0.10.1.tgz";
  };
  "@types/babel__core@7.20.5" = fetchurl {
    url = "https://registry.npmmirror.com/@types/babel__core/-/babel__core-7.20.5.tgz";
    hash = "sha512-qoQprZvz5wQFJwMDqeseRXWv3rqMvhgpbXFfVyWhbx9X47POIA6i/+dXefEmZKoAgOaTdaIgNSMqMIU61yRyzA==";
    name = "babel__core-7.20.5.tgz";
  };
  "@types/babel__generator@7.27.0" = fetchurl {
    url = "https://registry.npmmirror.com/@types/babel__generator/-/babel__generator-7.27.0.tgz";
    hash = "sha512-ufFd2Xi92OAVPYsy+P4n7/U7e68fex0+Ee8gSG9KX7eo084CWiQ4sdxktvdl0bOPupXtVJPY19zk6EwWqUQ8lg==";
    name = "babel__generator-7.27.0.tgz";
  };
  "@types/babel__template@7.4.4" = fetchurl {
    url = "https://registry.npmmirror.com/@types/babel__template/-/babel__template-7.4.4.tgz";
    hash = "sha512-h/NUaSyG5EyxBIp8YRxo4RMe2/qQgvyowRwVMzhYhBCONbW8PUsg4lkFMrhgZhUe5z3L3MiLDuvyJ/CaPa2A8A==";
    name = "babel__template-7.4.4.tgz";
  };
  "@types/babel__traverse@7.28.0" = fetchurl {
    url = "https://registry.npmmirror.com/@types/babel__traverse/-/babel__traverse-7.28.0.tgz";
    hash = "sha512-8PvcXf70gTDZBgt9ptxJ8elBeBjcLOAcOtoO/mPJjtji1+CdGbHgm77om1GrsPxsiE+uXIpNSK64UYaIwQXd4Q==";
    name = "babel__traverse-7.28.0.tgz";
  };
  "@types/estree@1.0.8" = fetchurl {
    url = "https://registry.npmmirror.com/@types/estree/-/estree-1.0.8.tgz";
    hash = "sha512-dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
    name = "estree-1.0.8.tgz";
  };
  "@types/json-schema@7.0.15" = fetchurl {
    url = "https://registry.npmmirror.com/@types/json-schema/-/json-schema-7.0.15.tgz";
    hash = "sha512-5+fP8P8MFNC+AyZCDxrB2pkZFPGzqQWUzpSeuuVLvm8VMcorNYavBqoFcxK8bQz4Qsbn4oUEEem4wDLfcysGHA==";
    name = "json-schema-7.0.15.tgz";
  };
  "@types/node@24.9.1" = fetchurl {
    url = "https://registry.npmmirror.com/@types/node/-/node-24.9.1.tgz";
    hash = "sha512-QoiaXANRkSXK6p0Duvt56W208du4P9Uye9hWLWgGMDTEoKPhuenzNcC4vGUmrNkiOKTlIrBoyNQYNpSwfEZXSg==";
    name = "node-24.9.1.tgz";
  };
  "@types/prop-types@15.7.15" = fetchurl {
    url = "https://registry.npmmirror.com/@types/prop-types/-/prop-types-15.7.15.tgz";
    hash = "sha512-F6bEyamV9jKGAFBEmlQnesRPGOQqS2+Uwi0Em15xenOxHaf2hv6L8YCVn3rPdPJOiJfPiCnLIRyvwVaqMY3MIw==";
    name = "prop-types-15.7.15.tgz";
  };
  "@types/react-dom@18.3.7" = fetchurl {
    url = "https://registry.npmmirror.com/@types/react-dom/-/react-dom-18.3.7.tgz";
    hash = "sha512-MEe3UeoENYVFXzoXEWsvcpg6ZvlrFNlOQ7EOsvhI3CfAXwzPfO8Qwuxd40nepsYKqyyVQnTdEfv68q91yLcKrQ==";
    name = "react-dom-18.3.7.tgz";
  };
  "@types/react@18.3.26" = fetchurl {
    url = "https://registry.npmmirror.com/@types/react/-/react-18.3.26.tgz";
    hash = "sha512-RFA/bURkcKzx/X9oumPG9Vp3D3JUgus/d0b67KB0t5S/raciymilkOa66olh78MUI92QLbEJevO7rvqU/kjwKA==";
    name = "react-18.3.26.tgz";
  };
  "@typescript-eslint/eslint-plugin@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/eslint-plugin/-/eslint-plugin-8.49.0.tgz";
    hash = "sha512-JXij0vzIaTtCwu6SxTh8qBc66kmf1xs7pI4UOiMDFVct6q86G0Zs7KRcEoJgY3Cav3x5Tq0MF5jwgpgLqgKG3A==";
    name = "eslint-plugin-8.49.0.tgz";
  };
  "@typescript-eslint/parser@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/parser/-/parser-8.49.0.tgz";
    hash = "sha512-N9lBGA9o9aqb1hVMc9hzySbhKibHmB+N3IpoShyV6HyQYRGIhlrO5rQgttypi+yEeKsKI4idxC8Jw6gXKD4THA==";
    name = "parser-8.49.0.tgz";
  };
  "@typescript-eslint/project-service@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/project-service/-/project-service-8.49.0.tgz";
    hash = "sha512-/wJN0/DKkmRUMXjZUXYZpD1NEQzQAAn9QWfGwo+Ai8gnzqH7tvqS7oNVdTjKqOcPyVIdZdyCMoqN66Ia789e7g==";
    name = "project-service-8.49.0.tgz";
  };
  "@typescript-eslint/scope-manager@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/scope-manager/-/scope-manager-8.49.0.tgz";
    hash = "sha512-npgS3zi+/30KSOkXNs0LQXtsg9ekZ8OISAOLGWA/ZOEn0ZH74Ginfl7foziV8DT+D98WfQ5Kopwqb/PZOaIJGg==";
    name = "scope-manager-8.49.0.tgz";
  };
  "@typescript-eslint/tsconfig-utils@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/tsconfig-utils/-/tsconfig-utils-8.49.0.tgz";
    hash = "sha512-8prixNi1/6nawsRYxet4YOhnbW+W9FK/bQPxsGB1D3ZrDzbJ5FXw5XmzxZv82X3B+ZccuSxo/X8q9nQ+mFecWA==";
    name = "tsconfig-utils-8.49.0.tgz";
  };
  "@typescript-eslint/type-utils@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/type-utils/-/type-utils-8.49.0.tgz";
    hash = "sha512-KTExJfQ+svY8I10P4HdxKzWsvtVnsuCifU5MvXrRwoP2KOlNZ9ADNEWWsQTJgMxLzS5VLQKDjkCT/YzgsnqmZg==";
    name = "type-utils-8.49.0.tgz";
  };
  "@typescript-eslint/types@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/types/-/types-8.49.0.tgz";
    hash = "sha512-e9k/fneezorUo6WShlQpMxXh8/8wfyc+biu6tnAqA81oWrEic0k21RHzP9uqqpyBBeBKu4T+Bsjy9/b8u7obXQ==";
    name = "types-8.49.0.tgz";
  };
  "@typescript-eslint/typescript-estree@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/typescript-estree/-/typescript-estree-8.49.0.tgz";
    hash = "sha512-jrLdRuAbPfPIdYNppHJ/D0wN+wwNfJ32YTAm10eJVsFmrVpXQnDWBn8niCSMlWjvml8jsce5E/O+86IQtTbJWA==";
    name = "typescript-estree-8.49.0.tgz";
  };
  "@typescript-eslint/utils@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/utils/-/utils-8.49.0.tgz";
    hash = "sha512-N3W7rJw7Rw+z1tRsHZbK395TWSYvufBXumYtEGzypgMUthlg0/hmCImeA8hgO2d2G4pd7ftpxxul2J8OdtdaFA==";
    name = "utils-8.49.0.tgz";
  };
  "@typescript-eslint/visitor-keys@8.49.0" = fetchurl {
    url = "https://registry.npmmirror.com/@typescript-eslint/visitor-keys/-/visitor-keys-8.49.0.tgz";
    hash = "sha512-LlKaciDe3GmZFphXIc79THF/YYBugZ7FS1pO581E/edlVVNbZKDy93evqmrfQ9/Y4uN0vVhX4iuchq26mK/iiA==";
    name = "visitor-keys-8.49.0.tgz";
  };
  "@vitejs/plugin-react@4.7.0" = fetchurl {
    url = "https://registry.npmmirror.com/@vitejs/plugin-react/-/plugin-react-4.7.0.tgz";
    hash = "sha512-gUu9hwfWvvEDBBmgtAowQCojwZmJ5mcLn3aufeCsitijs3+f2NsrPtlAWIR6OPiqljl96GVCUbLe0HyqIpVaoA==";
    name = "plugin-react-4.7.0.tgz";
  };
  "acorn-jsx@5.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
    hash = "sha512-rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
    name = "acorn-jsx-5.3.2.tgz";
  };
  "acorn@8.15.0" = fetchurl {
    url = "https://registry.npmmirror.com/acorn/-/acorn-8.15.0.tgz";
    hash = "sha512-NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
    name = "acorn-8.15.0.tgz";
  };
  "ajv@6.12.6" = fetchurl {
    url = "https://registry.npmmirror.com/ajv/-/ajv-6.12.6.tgz";
    hash = "sha512-j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
    name = "ajv-6.12.6.tgz";
  };
  "ansi-styles@4.3.0" = fetchurl {
    url = "https://registry.npmmirror.com/ansi-styles/-/ansi-styles-4.3.0.tgz";
    hash = "sha512-zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
    name = "ansi-styles-4.3.0.tgz";
  };
  "argparse@2.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/argparse/-/argparse-2.0.1.tgz";
    hash = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
    name = "argparse-2.0.1.tgz";
  };
  "balanced-match@1.0.2" = fetchurl {
    url = "https://registry.npmmirror.com/balanced-match/-/balanced-match-1.0.2.tgz";
    hash = "sha512-3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
    name = "balanced-match-1.0.2.tgz";
  };
  "baseline-browser-mapping@2.8.20" = fetchurl {
    url = "https://registry.npmmirror.com/baseline-browser-mapping/-/baseline-browser-mapping-2.8.20.tgz";
    hash = "sha512-JMWsdF+O8Orq3EMukbUN1QfbLK9mX2CkUmQBcW2T0s8OmdAUL5LLM/6wFwSrqXzlXB13yhyK9gTKS1rIizOduQ==";
    name = "baseline-browser-mapping-2.8.20.tgz";
  };
  "brace-expansion@1.1.12" = fetchurl {
    url = "https://registry.npmmirror.com/brace-expansion/-/brace-expansion-1.1.12.tgz";
    hash = "sha512-9T9UjW3r0UW5c1Q7GTwllptXwhvYmEzFhzMfZ9H7FQWt+uZePjZPjBP/W1ZEyZ1twGWom5/56TF4lPcqjnDHcg==";
    name = "brace-expansion-1.1.12.tgz";
  };
  "brace-expansion@2.0.2" = fetchurl {
    url = "https://registry.npmmirror.com/brace-expansion/-/brace-expansion-2.0.2.tgz";
    hash = "sha512-Jt0vHyM+jmUBqojB7E1NIYadt0vI0Qxjxd2TErW94wDz+E2LAm5vKMXXwg6ZZBTHPuUlDgQHKXvjGBdfcF1ZDQ==";
    name = "brace-expansion-2.0.2.tgz";
  };
  "browserslist@4.27.0" = fetchurl {
    url = "https://registry.npmmirror.com/browserslist/-/browserslist-4.27.0.tgz";
    hash = "sha512-AXVQwdhot1eqLihwasPElhX2tAZiBjWdJ9i/Zcj2S6QYIjkx62OKSfnobkriB81C3l4w0rVy3Nt4jaTBltYEpw==";
    name = "browserslist-4.27.0.tgz";
  };
  "callsites@3.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/callsites/-/callsites-3.1.0.tgz";
    hash = "sha512-P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
    name = "callsites-3.1.0.tgz";
  };
  "caniuse-lite@1.0.30001751" = fetchurl {
    url = "https://registry.npmmirror.com/caniuse-lite/-/caniuse-lite-1.0.30001751.tgz";
    hash = "sha512-A0QJhug0Ly64Ii3eIqHu5X51ebln3k4yTUkY1j8drqpWHVreg/VLijN48cZ1bYPiqOQuqpkIKnzr/Ul8V+p6Cw==";
    name = "caniuse-lite-1.0.30001751.tgz";
  };
  "chalk@4.1.2" = fetchurl {
    url = "https://registry.npmmirror.com/chalk/-/chalk-4.1.2.tgz";
    hash = "sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
    name = "chalk-4.1.2.tgz";
  };
  "color-convert@2.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/color-convert/-/color-convert-2.0.1.tgz";
    hash = "sha512-RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
    name = "color-convert-2.0.1.tgz";
  };
  "color-name@1.1.4" = fetchurl {
    url = "https://registry.npmmirror.com/color-name/-/color-name-1.1.4.tgz";
    hash = "sha512-dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
    name = "color-name-1.1.4.tgz";
  };
  "concat-map@0.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/concat-map/-/concat-map-0.0.1.tgz";
    hash = "sha512-/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
    name = "concat-map-0.0.1.tgz";
  };
  "convert-source-map@2.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/convert-source-map/-/convert-source-map-2.0.0.tgz";
    hash = "sha512-Kvp459HrV2FEJ1CAsi1Ku+MY3kasH19TFykTz2xWmMeq6bk2NU3XXvfJ+Q61m0xktWwt+1HSYf3JZsTms3aRJg==";
    name = "convert-source-map-2.0.0.tgz";
  };
  "cross-spawn@7.0.6" = fetchurl {
    url = "https://registry.npmmirror.com/cross-spawn/-/cross-spawn-7.0.6.tgz";
    hash = "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
    name = "cross-spawn-7.0.6.tgz";
  };
  "csstype@3.1.3" = fetchurl {
    url = "https://registry.npmmirror.com/csstype/-/csstype-3.1.3.tgz";
    hash = "sha512-M1uQkMl8rQK/szD0LNhtqxIPLpimGm8sOBwU7lLnCpSbTyY3yeU1Vc7l4KT5zT4s/yOxHH5O7tIuuLOCnLADRw==";
    name = "csstype-3.1.3.tgz";
  };
  "debug@4.4.3" = fetchurl {
    url = "https://registry.npmmirror.com/debug/-/debug-4.4.3.tgz";
    hash = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
    name = "debug-4.4.3.tgz";
  };
  "deep-is@0.1.4" = fetchurl {
    url = "https://registry.npmmirror.com/deep-is/-/deep-is-0.1.4.tgz";
    hash = "sha512-oIPzksmTg4/MriiaYGO+okXDT7ztn/w3Eptv/+gSIdMdKsJo0u4CfYNFJPy+4SKMuCqGw2wxnA+URMg3t8a/bQ==";
    name = "deep-is-0.1.4.tgz";
  };
  "detect-libc@2.1.2" = fetchurl {
    url = "https://registry.npmmirror.com/detect-libc/-/detect-libc-2.1.2.tgz";
    hash = "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==";
    name = "detect-libc-2.1.2.tgz";
  };
  "electron-to-chromium@1.5.240" = fetchurl {
    url = "https://registry.npmmirror.com/electron-to-chromium/-/electron-to-chromium-1.5.240.tgz";
    hash = "sha512-OBwbZjWgrCOH+g6uJsA2/7Twpas2OlepS9uvByJjR2datRDuKGYeD+nP8lBBks2qnB7bGJNHDUx7c/YLaT3QMQ==";
    name = "electron-to-chromium-1.5.240.tgz";
  };
  "enhanced-resolve@5.18.3" = fetchurl {
    url = "https://registry.npmmirror.com/enhanced-resolve/-/enhanced-resolve-5.18.3.tgz";
    hash = "sha512-d4lC8xfavMeBjzGr2vECC3fsGXziXZQyJxD868h2M/mBI3PwAuODxAkLkq5HYuvrPYcUtiLzsTo8U3PgX3Ocww==";
    name = "enhanced-resolve-5.18.3.tgz";
  };
  "esbuild@0.25.11" = fetchurl {
    url = "https://registry.npmmirror.com/esbuild/-/esbuild-0.25.11.tgz";
    hash = "sha512-KohQwyzrKTQmhXDW1PjCv3Tyspn9n5GcY2RTDqeORIdIJY8yKIF7sTSopFmn/wpMPW4rdPXI0UE5LJLuq3bx0Q==";
    name = "esbuild-0.25.11.tgz";
  };
  "escalade@3.2.0" = fetchurl {
    url = "https://registry.npmmirror.com/escalade/-/escalade-3.2.0.tgz";
    hash = "sha512-WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
    name = "escalade-3.2.0.tgz";
  };
  "escape-string-regexp@4.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
    hash = "sha512-TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
    name = "escape-string-regexp-4.0.0.tgz";
  };
  "eslint-plugin-i18next@6.1.3" = fetchurl {
    url = "https://registry.npmmirror.com/eslint-plugin-i18next/-/eslint-plugin-i18next-6.1.3.tgz";
    hash = "sha512-z/h4oBRd9wI1ET60HqcLSU6XPeAh/EPOrBBTyCdkWeMoYrWAaUVA+DOQkWTiNIyCltG4NTmy62SQisVXxoXurw==";
    name = "eslint-plugin-i18next-6.1.3.tgz";
  };
  "eslint-scope@8.4.0" = fetchurl {
    url = "https://registry.npmmirror.com/eslint-scope/-/eslint-scope-8.4.0.tgz";
    hash = "sha512-sNXOfKCn74rt8RICKMvJS7XKV/Xk9kA7DyJr8mJik3S7Cwgy3qlkkmyS2uQB3jiJg6VNdZd/pDBJu0nvG2NlTg==";
    name = "eslint-scope-8.4.0.tgz";
  };
  "eslint-visitor-keys@3.4.3" = fetchurl {
    url = "https://registry.npmmirror.com/eslint-visitor-keys/-/eslint-visitor-keys-3.4.3.tgz";
    hash = "sha512-wpc+LXeiyiisxPlEkUzU6svyS1frIO3Mgxj1fdy7Pm8Ygzguax2N3Fa/D/ag1WqbOprdI+uY6wMUl8/a2G+iag==";
    name = "eslint-visitor-keys-3.4.3.tgz";
  };
  "eslint-visitor-keys@4.2.1" = fetchurl {
    url = "https://registry.npmmirror.com/eslint-visitor-keys/-/eslint-visitor-keys-4.2.1.tgz";
    hash = "sha512-Uhdk5sfqcee/9H/rCOJikYz67o0a2Tw2hGRPOG2Y1R2dg7brRe1uG0yaNQDHu+TO/uQPF/5eCapvYSmHUjt7JQ==";
    name = "eslint-visitor-keys-4.2.1.tgz";
  };
  "eslint@9.39.1" = fetchurl {
    url = "https://registry.npmmirror.com/eslint/-/eslint-9.39.1.tgz";
    hash = "sha512-BhHmn2yNOFA9H9JmmIVKJmd288g9hrVRDkdoIgRCRuSySRUHH7r/DI6aAXW9T1WwUuY3DFgrcaqB+deURBLR5g==";
    name = "eslint-9.39.1.tgz";
  };
  "espree@10.4.0" = fetchurl {
    url = "https://registry.npmmirror.com/espree/-/espree-10.4.0.tgz";
    hash = "sha512-j6PAQ2uUr79PZhBjP5C5fhl8e39FmRnOjsD5lGnWrFU8i2G776tBK7+nP8KuQUTTyAZUwfQqXAgrVH5MbH9CYQ==";
    name = "espree-10.4.0.tgz";
  };
  "esquery@1.6.0" = fetchurl {
    url = "https://registry.npmmirror.com/esquery/-/esquery-1.6.0.tgz";
    hash = "sha512-ca9pw9fomFcKPvFLXhBKUK90ZvGibiGOvRJNbjljY7s7uq/5YO4BOzcYtJqExdx99rF6aAcnRxHmcUHcz6sQsg==";
    name = "esquery-1.6.0.tgz";
  };
  "esrecurse@4.3.0" = fetchurl {
    url = "https://registry.npmmirror.com/esrecurse/-/esrecurse-4.3.0.tgz";
    hash = "sha512-KmfKL3b6G+RXvP8N1vr3Tq1kL/oCFgn2NYXEtqP8/L3pKapUA4G8cFVaoF3SU323CD4XypR/ffioHmkti6/Tag==";
    name = "esrecurse-4.3.0.tgz";
  };
  "estraverse@5.3.0" = fetchurl {
    url = "https://registry.npmmirror.com/estraverse/-/estraverse-5.3.0.tgz";
    hash = "sha512-MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
    name = "estraverse-5.3.0.tgz";
  };
  "esutils@2.0.3" = fetchurl {
    url = "https://registry.npmmirror.com/esutils/-/esutils-2.0.3.tgz";
    hash = "sha512-kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
    name = "esutils-2.0.3.tgz";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmmirror.com/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
    name = "fast-deep-equal-3.1.3.tgz";
  };
  "fast-json-stable-stringify@2.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
    hash = "sha512-lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
    name = "fast-json-stable-stringify-2.1.0.tgz";
  };
  "fast-levenshtein@2.0.6" = fetchurl {
    url = "https://registry.npmmirror.com/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
    hash = "sha512-DCXu6Ifhqcks7TZKY3Hxp3y6qphY5SJZmrWMDrKcERSOXWQdMhU9Ig/PYrzyw/ul9jOIyh0N4M0tbC5hodg8dw==";
    name = "fast-levenshtein-2.0.6.tgz";
  };
  "fdir@6.5.0" = fetchurl {
    url = "https://registry.npmmirror.com/fdir/-/fdir-6.5.0.tgz";
    hash = "sha512-tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
    name = "fdir-6.5.0.tgz";
  };
  "file-entry-cache@8.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/file-entry-cache/-/file-entry-cache-8.0.0.tgz";
    hash = "sha512-XXTUwCvisa5oacNGRP9SfNtYBNAMi+RPwBFmblZEF7N7swHYQS6/Zfk7SRwx4D5j3CH211YNRco1DEMNVfZCnQ==";
    name = "file-entry-cache-8.0.0.tgz";
  };
  "find-up@5.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/find-up/-/find-up-5.0.0.tgz";
    hash = "sha512-78/PXT1wlLLDgTzDs7sjq9hzz0vXD+zn+7wypEe4fXQxCmdmqfGsEPQxmiCSQI3ajFV91bVSsvNtrJRiW6nGng==";
    name = "find-up-5.0.0.tgz";
  };
  "flat-cache@4.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/flat-cache/-/flat-cache-4.0.1.tgz";
    hash = "sha512-f7ccFPK3SXFHpx15UIGyRJ/FJQctuKZ0zVuN3frBo4HnK3cay9VEW0R6yPYFHC0AgqhukPzKjq22t5DmAyqGyw==";
    name = "flat-cache-4.0.1.tgz";
  };
  "flatted@3.3.3" = fetchurl {
    url = "https://registry.npmmirror.com/flatted/-/flatted-3.3.3.tgz";
    hash = "sha512-GX+ysw4PBCz0PzosHDepZGANEuFCMLrnRTiEy9McGjmkCQYwRq4A/X786G/fjM/+OjsWSU1ZrY5qyARZmO/uwg==";
    name = "flatted-3.3.3.tgz";
  };
  "fsevents@2.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/fsevents/-/fsevents-2.3.2.tgz";
    hash = "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
    name = "fsevents-2.3.2.tgz";
  };
  "fsevents@2.3.3" = fetchurl {
    url = "https://registry.npmmirror.com/fsevents/-/fsevents-2.3.3.tgz";
    hash = "sha512-5xoDfX+fL7faATnagmWPpbFtwh/R77WmMMqqHGS65C3vvB0YHrgF+B1YmZ3441tMj5n63k0212XNoJwzlhffQw==";
    name = "fsevents-2.3.3.tgz";
  };
  "gensync@1.0.0-beta.2" = fetchurl {
    url = "https://registry.npmmirror.com/gensync/-/gensync-1.0.0-beta.2.tgz";
    hash = "sha512-3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
    name = "gensync-1.0.0-beta.2.tgz";
  };
  "glob-parent@6.0.2" = fetchurl {
    url = "https://registry.npmmirror.com/glob-parent/-/glob-parent-6.0.2.tgz";
    hash = "sha512-XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==";
    name = "glob-parent-6.0.2.tgz";
  };
  "globals@14.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/globals/-/globals-14.0.0.tgz";
    hash = "sha512-oahGvuMGQlPw/ivIYBjVSrWAfWLBeku5tpPE2fOPLi+WHffIWbuh2tCjhyQhTBPMf5E9jDEH4FOmTYgYwbKwtQ==";
    name = "globals-14.0.0.tgz";
  };
  "graceful-fs@4.2.11" = fetchurl {
    url = "https://registry.npmmirror.com/graceful-fs/-/graceful-fs-4.2.11.tgz";
    hash = "sha512-RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
    name = "graceful-fs-4.2.11.tgz";
  };
  "has-flag@4.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/has-flag/-/has-flag-4.0.0.tgz";
    hash = "sha512-EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
    name = "has-flag-4.0.0.tgz";
  };
  "html-parse-stringify@3.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/html-parse-stringify/-/html-parse-stringify-3.0.1.tgz";
    hash = "sha512-KknJ50kTInJ7qIScF3jeaFRpMpE8/lfiTdzf/twXyPBLAGrLRTmkz3AdTnKeh40X8k9L2fdYwEp/42WGXIRGcg==";
    name = "html-parse-stringify-3.0.1.tgz";
  };
  "i18next@25.7.2" = fetchurl {
    url = "https://registry.npmmirror.com/i18next/-/i18next-25.7.2.tgz";
    hash = "sha512-58b4kmLpLv1buWUEwegMDUqZVR5J+rT+WTRFaBGL7lxDuJQQ0NrJFrq+eT2N94aYVR1k1Sr13QITNOL88tZCuw==";
    name = "i18next-25.7.2.tgz";
  };
  "ignore@5.3.2" = fetchurl {
    url = "https://registry.npmmirror.com/ignore/-/ignore-5.3.2.tgz";
    hash = "sha512-hsBTNUqQTDwkWtcdYI2i06Y/nUBEsNEDJKjWdigLvegy8kDuJAS8uRlpkkcQpyEXL0Z/pjDy5HBmMjRCJ2gq+g==";
    name = "ignore-5.3.2.tgz";
  };
  "ignore@7.0.5" = fetchurl {
    url = "https://registry.npmmirror.com/ignore/-/ignore-7.0.5.tgz";
    hash = "sha512-Hs59xBNfUIunMFgWAbGX5cq6893IbWg4KnrjbYwX3tx0ztorVgTDA6B2sxf8ejHJ4wz8BqGUMYlnzNBer5NvGg==";
    name = "ignore-7.0.5.tgz";
  };
  "immer@11.1.3" = fetchurl {
    url = "https://registry.npmmirror.com/immer/-/immer-11.1.3.tgz";
    hash = "sha512-6jQTc5z0KJFtr1UgFpIL3N9XSC3saRaI9PwWtzM2pSqkNGtiNkYY2OSwkOGDK2XcTRcLb1pi/aNkKZz0nxVH4Q==";
    name = "immer-11.1.3.tgz";
  };
  "import-fresh@3.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/import-fresh/-/import-fresh-3.3.1.tgz";
    hash = "sha512-TR3KfrTZTYLPB6jUjfx6MF9WcWrHL9su5TObK4ZkYgBdWKPOFoSoQIdEuTuR82pmtxH2spWG9h6etwfr1pLBqQ==";
    name = "import-fresh-3.3.1.tgz";
  };
  "imurmurhash@0.1.4" = fetchurl {
    url = "https://registry.npmmirror.com/imurmurhash/-/imurmurhash-0.1.4.tgz";
    hash = "sha512-JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
    name = "imurmurhash-0.1.4.tgz";
  };
  "is-extglob@2.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/is-extglob/-/is-extglob-2.1.1.tgz";
    hash = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
    name = "is-extglob-2.1.1.tgz";
  };
  "is-glob@4.0.3" = fetchurl {
    url = "https://registry.npmmirror.com/is-glob/-/is-glob-4.0.3.tgz";
    hash = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
    name = "is-glob-4.0.3.tgz";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
    name = "isexe-2.0.0.tgz";
  };
  "jiti@2.6.1" = fetchurl {
    url = "https://registry.npmmirror.com/jiti/-/jiti-2.6.1.tgz";
    hash = "sha512-ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
    name = "jiti-2.6.1.tgz";
  };
  "js-tokens@4.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/js-tokens/-/js-tokens-4.0.0.tgz";
    hash = "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
    name = "js-tokens-4.0.0.tgz";
  };
  "js-yaml@4.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/js-yaml/-/js-yaml-4.3.1.tgz";
    hash = "sha512-CY6crGq313MX8GkwvB7tzgp99vjQxY1++5y10/BKN/GUfHqWaOGQMNZkBvqSzsZKWk/ijwHlWzzkLulsGHhjWQ==";
    name = "js-yaml-4.3.1.tgz";
  };
  "jsesc@3.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/jsesc/-/jsesc-3.1.0.tgz";
    hash = "sha512-/sM3dO2FOzXjKQhJuo0Q173wf2KOo8t4I8vHy6lF9poUp7bKT0/NHE8fPX23PwfhnykfqnC2xRxOnVw5XuGIaA==";
    name = "jsesc-3.1.0.tgz";
  };
  "json-buffer@3.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/json-buffer/-/json-buffer-3.0.1.tgz";
    hash = "sha512-4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
    name = "json-buffer-3.0.1.tgz";
  };
  "json-schema-traverse@0.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
    hash = "sha512-xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
    name = "json-schema-traverse-0.4.1.tgz";
  };
  "json-stable-stringify-without-jsonify@1.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
    hash = "sha512-Bdboy+l7tA3OGW6FjyFHWkP5LuByj1Tk33Ljyq0axyzdk9//JSi2u3fP1QSmd1KNwq6VOKYGlAu87CisVir6Pw==";
    name = "json-stable-stringify-without-jsonify-1.0.1.tgz";
  };
  "json5@2.2.3" = fetchurl {
    url = "https://registry.npmmirror.com/json5/-/json5-2.2.3.tgz";
    hash = "sha512-XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
    name = "json5-2.2.3.tgz";
  };
  "keyv@4.5.4" = fetchurl {
    url = "https://registry.npmmirror.com/keyv/-/keyv-4.5.4.tgz";
    hash = "sha512-oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
    name = "keyv-4.5.4.tgz";
  };
  "levn@0.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/levn/-/levn-0.4.1.tgz";
    hash = "sha512-+bT2uH4E5LGE7h/n3evcS/sQlJXCpIp6ym8OWJ5eV6+67Dsql/LaaT7qJBAt2rzfoa/5QBGBhxDix1dMt2kQKQ==";
    name = "levn-0.4.1.tgz";
  };
  "lightningcss-android-arm64@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-android-arm64/-/lightningcss-android-arm64-1.30.2.tgz";
    hash = "sha512-BH9sEdOCahSgmkVhBLeU7Hc9DWeZ1Eb6wNS6Da8igvUwAe0sqROHddIlvU06q3WyXVEOYDZ6ykBZQnjTbmo4+A==";
    name = "lightningcss-android-arm64-1.30.2.tgz";
  };
  "lightningcss-darwin-arm64@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.30.2.tgz";
    hash = "sha512-ylTcDJBN3Hp21TdhRT5zBOIi73P6/W0qwvlFEk22fkdXchtNTOU4Qc37SkzV+EKYxLouZ6M4LG9NfZ1qkhhBWA==";
    name = "lightningcss-darwin-arm64-1.30.2.tgz";
  };
  "lightningcss-darwin-x64@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.30.2.tgz";
    hash = "sha512-oBZgKchomuDYxr7ilwLcyms6BCyLn0z8J0+ZZmfpjwg9fRVZIR5/GMXd7r9RH94iDhld3UmSjBM6nXWM2TfZTQ==";
    name = "lightningcss-darwin-x64-1.30.2.tgz";
  };
  "lightningcss-freebsd-x64@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.30.2.tgz";
    hash = "sha512-c2bH6xTrf4BDpK8MoGG4Bd6zAMZDAXS569UxCAGcA7IKbHNMlhGQ89eRmvpIUGfKWNVdbhSbkQaWhEoMGmGslA==";
    name = "lightningcss-freebsd-x64-1.30.2.tgz";
  };
  "lightningcss-linux-arm-gnueabihf@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.30.2.tgz";
    hash = "sha512-eVdpxh4wYcm0PofJIZVuYuLiqBIakQ9uFZmipf6LF/HRj5Bgm0eb3qL/mr1smyXIS1twwOxNWndd8z0E374hiA==";
    name = "lightningcss-linux-arm-gnueabihf-1.30.2.tgz";
  };
  "lightningcss-linux-arm64-gnu@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.30.2.tgz";
    hash = "sha512-UK65WJAbwIJbiBFXpxrbTNArtfuznvxAJw4Q2ZGlU8kPeDIWEX1dg3rn2veBVUylA2Ezg89ktszWbaQnxD/e3A==";
    name = "lightningcss-linux-arm64-gnu-1.30.2.tgz";
  };
  "lightningcss-linux-arm64-musl@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.30.2.tgz";
    hash = "sha512-5Vh9dGeblpTxWHpOx8iauV02popZDsCYMPIgiuw97OJ5uaDsL86cnqSFs5LZkG3ghHoX5isLgWzMs+eD1YzrnA==";
    name = "lightningcss-linux-arm64-musl-1.30.2.tgz";
  };
  "lightningcss-linux-x64-gnu@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.30.2.tgz";
    hash = "sha512-Cfd46gdmj1vQ+lR6VRTTadNHu6ALuw2pKR9lYq4FnhvgBc4zWY1EtZcAc6EffShbb1MFrIPfLDXD6Xprbnni4w==";
    name = "lightningcss-linux-x64-gnu-1.30.2.tgz";
  };
  "lightningcss-linux-x64-musl@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.30.2.tgz";
    hash = "sha512-XJaLUUFXb6/QG2lGIW6aIk6jKdtjtcffUT0NKvIqhSBY3hh9Ch+1LCeH80dR9q9LBjG3ewbDjnumefsLsP6aiA==";
    name = "lightningcss-linux-x64-musl-1.30.2.tgz";
  };
  "lightningcss-win32-arm64-msvc@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.30.2.tgz";
    hash = "sha512-FZn+vaj7zLv//D/192WFFVA0RgHawIcHqLX9xuWiQt7P0PtdFEVaxgF9rjM/IRYHQXNnk61/H/gb2Ei+kUQ4xQ==";
    name = "lightningcss-win32-arm64-msvc-1.30.2.tgz";
  };
  "lightningcss-win32-x64-msvc@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.30.2.tgz";
    hash = "sha512-5g1yc73p+iAkid5phb4oVFMB45417DkRevRbt/El/gKXJk4jid+vPFF/AXbxn05Aky8PapwzZrdJShv5C0avjw==";
    name = "lightningcss-win32-x64-msvc-1.30.2.tgz";
  };
  "lightningcss@1.30.2" = fetchurl {
    url = "https://registry.npmmirror.com/lightningcss/-/lightningcss-1.30.2.tgz";
    hash = "sha512-utfs7Pr5uJyyvDETitgsaqSyjCb2qNRAtuqUeWIAKztsOYdcACf2KtARYXg2pSvhkt+9NfoaNY7fxjl6nuMjIQ==";
    name = "lightningcss-1.30.2.tgz";
  };
  "locate-path@6.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/locate-path/-/locate-path-6.0.0.tgz";
    hash = "sha512-iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw==";
    name = "locate-path-6.0.0.tgz";
  };
  "lodash.merge@4.6.2" = fetchurl {
    url = "https://registry.npmmirror.com/lodash.merge/-/lodash.merge-4.6.2.tgz";
    hash = "sha512-0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
    name = "lodash.merge-4.6.2.tgz";
  };
  "lodash@4.17.21" = fetchurl {
    url = "https://registry.npmmirror.com/lodash/-/lodash-4.17.21.tgz";
    hash = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
    name = "lodash-4.17.21.tgz";
  };
  "loose-envify@1.4.0" = fetchurl {
    url = "https://registry.npmmirror.com/loose-envify/-/loose-envify-1.4.0.tgz";
    hash = "sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
    name = "loose-envify-1.4.0.tgz";
  };
  "lru-cache@5.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/lru-cache/-/lru-cache-5.1.1.tgz";
    hash = "sha512-KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
    name = "lru-cache-5.1.1.tgz";
  };
  "lucide-react@0.542.0" = fetchurl {
    url = "https://registry.npmmirror.com/lucide-react/-/lucide-react-0.542.0.tgz";
    hash = "sha512-w3hD8/SQB7+lzU2r4VdFyzzOzKnUjTZIF/MQJGSSvni7Llewni4vuViRppfRAa2guOsY5k4jZyxw/i9DQHv+dw==";
    name = "lucide-react-0.542.0.tgz";
  };
  "magic-string@0.30.21" = fetchurl {
    url = "https://registry.npmmirror.com/magic-string/-/magic-string-0.30.21.tgz";
    hash = "sha512-vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==";
    name = "magic-string-0.30.21.tgz";
  };
  "minimatch@3.1.2" = fetchurl {
    url = "https://registry.npmmirror.com/minimatch/-/minimatch-3.1.2.tgz";
    hash = "sha512-J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
    name = "minimatch-3.1.2.tgz";
  };
  "minimatch@9.0.5" = fetchurl {
    url = "https://registry.npmmirror.com/minimatch/-/minimatch-9.0.5.tgz";
    hash = "sha512-G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
    name = "minimatch-9.0.5.tgz";
  };
  "ms@2.1.3" = fetchurl {
    url = "https://registry.npmmirror.com/ms/-/ms-2.1.3.tgz";
    hash = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
    name = "ms-2.1.3.tgz";
  };
  "nanoid@3.3.11" = fetchurl {
    url = "https://registry.npmmirror.com/nanoid/-/nanoid-3.3.11.tgz";
    hash = "sha512-N8SpfPUnUp1bK+PMYW8qSWdl9U+wwNWI4QKxOYDy9JAro3WMX7p2OeVRF9v+347pnakNevPmiHhNmZ2HbFA76w==";
    name = "nanoid-3.3.11.tgz";
  };
  "natural-compare@1.4.0" = fetchurl {
    url = "https://registry.npmmirror.com/natural-compare/-/natural-compare-1.4.0.tgz";
    hash = "sha512-OWND8ei3VtNC9h7V60qff3SVobHr996CTwgxubgyQYEpg290h9J0buyECNNJexkFm5sOajh5G116RYA1c8ZMSw==";
    name = "natural-compare-1.4.0.tgz";
  };
  "node-releases@2.0.26" = fetchurl {
    url = "https://registry.npmmirror.com/node-releases/-/node-releases-2.0.26.tgz";
    hash = "sha512-S2M9YimhSjBSvYnlr5/+umAnPHE++ODwt5e2Ij6FoX45HA/s4vHdkDx1eax2pAPeAOqu4s9b7ppahsyEFdVqQA==";
    name = "node-releases-2.0.26.tgz";
  };
  "optionator@0.9.4" = fetchurl {
    url = "https://registry.npmmirror.com/optionator/-/optionator-0.9.4.tgz";
    hash = "sha512-6IpQ7mKUxRcZNLIObR0hz7lxsapSSIYNZJwXPGeF0mTVqGKFIXj1DQcMoT22S3ROcLyY/rz0PWaWZ9ayWmad9g==";
    name = "optionator-0.9.4.tgz";
  };
  "p-limit@3.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/p-limit/-/p-limit-3.1.0.tgz";
    hash = "sha512-TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
    name = "p-limit-3.1.0.tgz";
  };
  "p-locate@5.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/p-locate/-/p-locate-5.0.0.tgz";
    hash = "sha512-LaNjtRWUBY++zB5nE/NwcaoMylSPk+S+ZHNB1TzdbMJMny6dynpAGt7X/tl/QYq3TIeE6nxHppbo2LGymrG5Pw==";
    name = "p-locate-5.0.0.tgz";
  };
  "parent-module@1.0.1" = fetchurl {
    url = "https://registry.npmmirror.com/parent-module/-/parent-module-1.0.1.tgz";
    hash = "sha512-GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
    name = "parent-module-1.0.1.tgz";
  };
  "path-exists@4.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/path-exists/-/path-exists-4.0.0.tgz";
    hash = "sha512-ak9Qy5Q7jYb2Wwcey5Fpvg2KoAc/ZIhLSLOSBmRmygPsGwkVVt0fZa0qrtMz+m6tJTAHfZQ8FnmB4MG4LWy7/w==";
    name = "path-exists-4.0.0.tgz";
  };
  "path-key@3.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/path-key/-/path-key-3.1.1.tgz";
    hash = "sha512-ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
    name = "path-key-3.1.1.tgz";
  };
  "picocolors@1.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/picocolors/-/picocolors-1.1.1.tgz";
    hash = "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
    name = "picocolors-1.1.1.tgz";
  };
  "picomatch@4.0.3" = fetchurl {
    url = "https://registry.npmmirror.com/picomatch/-/picomatch-4.0.3.tgz";
    hash = "sha512-5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
    name = "picomatch-4.0.3.tgz";
  };
  "playwright-core@1.58.0" = fetchurl {
    url = "https://registry.npmmirror.com/playwright-core/-/playwright-core-1.58.0.tgz";
    hash = "sha512-aaoB1RWrdNi3//rOeKuMiS65UCcgOVljU46At6eFcOFPFHWtd2weHRRow6z/n+Lec0Lvu0k9ZPKJSjPugikirw==";
    name = "playwright-core-1.58.0.tgz";
  };
  "playwright@1.58.0" = fetchurl {
    url = "https://registry.npmmirror.com/playwright/-/playwright-1.58.0.tgz";
    hash = "sha512-2SVA0sbPktiIY/MCOPX8e86ehA/e+tDNq+e5Y8qjKYti2Z/JG7xnronT/TXTIkKbYGWlCbuucZ6dziEgkoEjQQ==";
    name = "playwright-1.58.0.tgz";
  };
  "postcss@8.5.6" = fetchurl {
    url = "https://registry.npmmirror.com/postcss/-/postcss-8.5.6.tgz";
    hash = "sha512-3Ybi1tAuwAP9s0r1UQ2J4n5Y0G05bJkpUIO0/bI9MhwmD70S5aTWbXGBwxHrelT+XM1k6dM0pk+SwNkpTRN7Pg==";
    name = "postcss-8.5.6.tgz";
  };
  "prelude-ls@1.2.1" = fetchurl {
    url = "https://registry.npmmirror.com/prelude-ls/-/prelude-ls-1.2.1.tgz";
    hash = "sha512-vkcDPrRZo1QZLbn5RLGPpg/WmIQ65qoWWhcGKf/b5eplkkarX0m9z8ppCat4mlOqUsWpyNuYgO3VRyrYHSzX5g==";
    name = "prelude-ls-1.2.1.tgz";
  };
  "prettier@3.6.2" = fetchurl {
    url = "https://registry.npmmirror.com/prettier/-/prettier-3.6.2.tgz";
    hash = "sha512-I7AIg5boAr5R0FFtJ6rCfD+LFsWHp81dolrFD8S79U9tb8Az2nGrJncnMSnys+bpQJfRUzqs9hnA81OAA3hCuQ==";
    name = "prettier-3.6.2.tgz";
  };
  "punycode@2.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/punycode/-/punycode-2.3.1.tgz";
    hash = "sha512-vYt7UD1U9Wg6138shLtLOvdAu+8DsC/ilFtEVHcH+wydcSpNE20AfSOduf6MkRFahL5FY7X1oU7nKVZFtfq8Fg==";
    name = "punycode-2.3.1.tgz";
  };
  "react-dom@18.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/react-dom/-/react-dom-18.3.1.tgz";
    hash = "sha512-5m4nQKp+rZRb09LNH59GM4BxTh9251/ylbKIbpe7TpGxfJ+9kv6BLkLBXIjjspbgbnIBNqlI23tRnTWT0snUIw==";
    name = "react-dom-18.3.1.tgz";
  };
  "react-i18next@16.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/react-i18next/-/react-i18next-16.4.1.tgz";
    hash = "sha512-GzsYomxb1/uE7nlJm0e1qQ8f+W9I3Xirh9VoycZIahk6C8Pmv/9Fd0ek6zjf1FSgtGLElDGqwi/4FOHEGUbsEQ==";
    name = "react-i18next-16.4.1.tgz";
  };
  "react-refresh@0.17.0" = fetchurl {
    url = "https://registry.npmmirror.com/react-refresh/-/react-refresh-0.17.0.tgz";
    hash = "sha512-z6F7K9bV85EfseRCp2bzrpyQ0Gkw1uLoCel9XBVWPg/TjRj94SkJzUTGfOa4bs7iJvBWtQG0Wq7wnI0syw3EBQ==";
    name = "react-refresh-0.17.0.tgz";
  };
  "react@18.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/react/-/react-18.3.1.tgz";
    hash = "sha512-wS+hAgJShR0KhEvPJArfuPVN1+Hz1t0Y6n5jLrGQbkb4urgPE/0Rve+1kMB1v/oWgHgm4WIcV+i7F2pTVj+2iQ==";
    name = "react-18.3.1.tgz";
  };
  "requireindex@1.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/requireindex/-/requireindex-1.1.0.tgz";
    hash = "sha512-LBnkqsDE7BZKvqylbmn7lTIVdpx4K/QCduRATpO5R+wtPmky/a8pN1bO2D6wXppn1497AJF9mNjqAXr6bdl9jg==";
    name = "requireindex-1.1.0.tgz";
  };
  "resolve-from@4.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/resolve-from/-/resolve-from-4.0.0.tgz";
    hash = "sha512-pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
    name = "resolve-from-4.0.0.tgz";
  };
  "rollup@4.52.5" = fetchurl {
    url = "https://registry.npmmirror.com/rollup/-/rollup-4.52.5.tgz";
    hash = "sha512-3GuObel8h7Kqdjt0gxkEzaifHTqLVW56Y/bjN7PSQtkKr0w3V/QYSdt6QWYtd7A1xUtYQigtdUfgj1RvWVtorw==";
    name = "rollup-4.52.5.tgz";
  };
  "scheduler@0.23.2" = fetchurl {
    url = "https://registry.npmmirror.com/scheduler/-/scheduler-0.23.2.tgz";
    hash = "sha512-UOShsPwz7NrMUqhR6t0hWjFduvOzbtv7toDH1/hIrfRNIDBnnBWd0CwJTGvTpngVlmwGCdP9/Zl/tVrDqcuYzQ==";
    name = "scheduler-0.23.2.tgz";
  };
  "semver@6.3.1" = fetchurl {
    url = "https://registry.npmmirror.com/semver/-/semver-6.3.1.tgz";
    hash = "sha512-BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
    name = "semver-6.3.1.tgz";
  };
  "semver@7.7.3" = fetchurl {
    url = "https://registry.npmmirror.com/semver/-/semver-7.7.3.tgz";
    hash = "sha512-SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
    name = "semver-7.7.3.tgz";
  };
  "shebang-command@2.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/shebang-command/-/shebang-command-2.0.0.tgz";
    hash = "sha512-kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
    name = "shebang-command-2.0.0.tgz";
  };
  "shebang-regex@3.0.0" = fetchurl {
    url = "https://registry.npmmirror.com/shebang-regex/-/shebang-regex-3.0.0.tgz";
    hash = "sha512-7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
    name = "shebang-regex-3.0.0.tgz";
  };
  "sonner@2.0.7" = fetchurl {
    url = "https://registry.npmmirror.com/sonner/-/sonner-2.0.7.tgz";
    hash = "sha512-W6ZN4p58k8aDKA4XPcx2hpIQXBRAgyiWVkYhT7CvK6D3iAu7xjvVyhQHg2/iaKJZ1XVJ4r7XuwGL+WGEK37i9w==";
    name = "sonner-2.0.7.tgz";
  };
  "source-map-js@1.2.1" = fetchurl {
    url = "https://registry.npmmirror.com/source-map-js/-/source-map-js-1.2.1.tgz";
    hash = "sha512-UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
    name = "source-map-js-1.2.1.tgz";
  };
  "strip-json-comments@3.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/strip-json-comments/-/strip-json-comments-3.1.1.tgz";
    hash = "sha512-6fPc+R4ihwqP6N/aIv2f1gMH8lOVtWQHoqC4yK6oSDVVocumAsfCqjkXnqiYMhmMwS/mEHLp7Vehlt3ql6lEig==";
    name = "strip-json-comments-3.1.1.tgz";
  };
  "supports-color@7.2.0" = fetchurl {
    url = "https://registry.npmmirror.com/supports-color/-/supports-color-7.2.0.tgz";
    hash = "sha512-qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
    name = "supports-color-7.2.0.tgz";
  };
  "tailwindcss@4.1.16" = fetchurl {
    url = "https://registry.npmmirror.com/tailwindcss/-/tailwindcss-4.1.16.tgz";
    hash = "sha512-pONL5awpaQX4LN5eiv7moSiSPd/DLDzKVRJz8Q9PgzmAdd1R4307GQS2ZpfiN7ZmekdQrfhZZiSE5jkLR4WNaA==";
    name = "tailwindcss-4.1.16.tgz";
  };
  "tapable@2.3.0" = fetchurl {
    url = "https://registry.npmmirror.com/tapable/-/tapable-2.3.0.tgz";
    hash = "sha512-g9ljZiwki/LfxmQADO3dEY1CbpmXT5Hm2fJ+QaGKwSXUylMybePR7/67YW7jOrrvjEgL1Fmz5kzyAjWVWLlucg==";
    name = "tapable-2.3.0.tgz";
  };
  "tauri-plugin-macos-permissions-api@2.3.0" = fetchurl {
    url = "https://registry.npmmirror.com/tauri-plugin-macos-permissions-api/-/tauri-plugin-macos-permissions-api-2.3.0.tgz";
    hash = "sha512-pZp0jmDySysBqrGueknd1a7Rr4XEO9aXpMv9TNrT2PDHP0MSH20njieOagsFYJ5MCVb8A+wcaK0cIkjUC2dOww==";
    name = "tauri-plugin-macos-permissions-api-2.3.0.tgz";
  };
  "tinyglobby@0.2.15" = fetchurl {
    url = "https://registry.npmmirror.com/tinyglobby/-/tinyglobby-0.2.15.tgz";
    hash = "sha512-j2Zq4NyQYG5XMST4cbs02Ak8iJUdxRM0XI5QyxXuZOzKOINmWurp3smXu3y5wDcJrptwpSjgXHzIQxR0omXljQ==";
    name = "tinyglobby-0.2.15.tgz";
  };
  "ts-api-utils@2.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/ts-api-utils/-/ts-api-utils-2.1.0.tgz";
    hash = "sha512-CUgTZL1irw8u29bzrOD/nH85jqyc74D6SshFgujOIA7osm2Rz7dYH77agkx7H4FBNxDq7Cjf+IjaX/8zwFW+ZQ==";
    name = "ts-api-utils-2.1.0.tgz";
  };
  "tslib@2.8.1" = fetchurl {
    url = "https://registry.npmmirror.com/tslib/-/tslib-2.8.1.tgz";
    hash = "sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
    name = "tslib-2.8.1.tgz";
  };
  "type-check@0.4.0" = fetchurl {
    url = "https://registry.npmmirror.com/type-check/-/type-check-0.4.0.tgz";
    hash = "sha512-XleUoc9uwGXqjWwXaUTZAmzMcFZ5858QA2vvx1Ur5xIcixXIP+8LnFDgRplU30us6teqdlskFfu+ae4K79Ooew==";
    name = "type-check-0.4.0.tgz";
  };
  "typescript@5.6.3" = fetchurl {
    url = "https://registry.npmmirror.com/typescript/-/typescript-5.6.3.tgz";
    hash = "sha512-hjcS1mhfuyi4WW8IWtjP7brDrG2cuDZukyrYrSauoXGNgx0S7zceP07adYkJycEr56BOUTNPzbInooiN3fn1qw==";
    name = "typescript-5.6.3.tgz";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmmirror.com/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
    name = "undici-types-7.16.0.tgz";
  };
  "update-browserslist-db@1.1.4" = fetchurl {
    url = "https://registry.npmmirror.com/update-browserslist-db/-/update-browserslist-db-1.1.4.tgz";
    hash = "sha512-q0SPT4xyU84saUX+tomz1WLkxUbuaJnR1xWt17M7fJtEJigJeWUNGUqrauFXsHnqev9y9JTRGwk13tFBuKby4A==";
    name = "update-browserslist-db-1.1.4.tgz";
  };
  "uri-js@4.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/uri-js/-/uri-js-4.4.1.tgz";
    hash = "sha512-7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
    name = "uri-js-4.4.1.tgz";
  };
  "use-sync-external-store@1.6.0" = fetchurl {
    url = "https://registry.npmmirror.com/use-sync-external-store/-/use-sync-external-store-1.6.0.tgz";
    hash = "sha512-Pp6GSwGP/NrPIrxVFAIkOQeyw8lFenOHijQWkUTrDvrF4ALqylP2C/KCkeS9dpUM3KvYRQhna5vt7IL95+ZQ9w==";
    name = "use-sync-external-store-1.6.0.tgz";
  };
  "vite@6.4.1" = fetchurl {
    url = "https://registry.npmmirror.com/vite/-/vite-6.4.1.tgz";
    hash = "sha512-+Oxm7q9hDoLMyJOYfUYBuHQo+dkAloi33apOPP56pzj+vsdJDzr+j1NISE5pyaAuKL4A3UD34qd0lx5+kfKp2g==";
    name = "vite-6.4.1.tgz";
  };
  "void-elements@3.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/void-elements/-/void-elements-3.1.0.tgz";
    hash = "sha512-Dhxzh5HZuiHQhbvTW9AMetFfBHDMYpo23Uo9btPXgdYP+3T5S+p+jgNy7spra+veYhBP2dCSgxR/i2Y02h5/6w==";
    name = "void-elements-3.1.0.tgz";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmmirror.com/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
    name = "which-2.0.2.tgz";
  };
  "word-wrap@1.2.5" = fetchurl {
    url = "https://registry.npmmirror.com/word-wrap/-/word-wrap-1.2.5.tgz";
    hash = "sha512-BN22B5eaMMI9UMtjrGd5g5eCYPpCPDUy0FJXbYsaT5zYxjFOckS53SQDE3pWkVoWpHXVb3BrYcEN4Twa55B5cA==";
    name = "word-wrap-1.2.5.tgz";
  };
  "yallist@3.1.1" = fetchurl {
    url = "https://registry.npmmirror.com/yallist/-/yallist-3.1.1.tgz";
    hash = "sha512-a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
    name = "yallist-3.1.1.tgz";
  };
  "yaml@1.10.2" = fetchurl {
    url = "https://registry.npmmirror.com/yaml/-/yaml-1.10.2.tgz";
    hash = "sha512-r3vXyErRCYJ7wg28yvBY5VSoAF8ZvlcW9/BwUzEtUsjvX/DKs24dIkuwjtuprwJJHsbyUbLApepYTR1BN4uHrg==";
    name = "yaml-1.10.2.tgz";
  };
  "yocto-queue@0.1.0" = fetchurl {
    url = "https://registry.npmmirror.com/yocto-queue/-/yocto-queue-0.1.0.tgz";
    hash = "sha512-rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
    name = "yocto-queue-0.1.0.tgz";
  };
  "zustand@5.0.8" = fetchurl {
    url = "https://registry.npmmirror.com/zustand/-/zustand-5.0.8.tgz";
    hash = "sha512-gyPKpIaxY9XcO2vSMrLbiER7QMAMGOQZVRdJ6Zi782jkbzZygq5GI9nG8g+sMgitRtndwaBSl7uiqC49o1SSiw==";
    name = "zustand-5.0.8.tgz";
  };
}
